var words=[{"hard":"abandon","easy":"leave"},
{"hard":"abandoned","easy":"left"},
{"hard":"abandoning","easy":"leaving"},
{"hard":"abandons","easy":"leaves"},
{"hard":"abate","easy":"make less"},
{"hard":"abated","easy":"made less"},
{"hard":"abates","easy":"makes less"},
{"hard":"abating","easy":"making less"},
{"hard":"abbreviate","easy":"make shorter"},
{"hard":"abbreviated","easy":"made shorter"},
{"hard":"abbreviating","easy":"making shorter"},
{"hard":"abbreviation","easy":"short form"},
{"hard":"abdicate","easy":"give up"},
{"hard":"abdicates","easy":"gives up"},
{"hard":"abdicating","easy":"giving up"},
{"hard":"abduct","easy":"take away"},
{"hard":"abducted","easy":"taken away"},
{"hard":"abducting","easy":"taking away"},
{"hard":"abducts","easy":"takes away"},
{"hard":"abhor","easy":"hate"},
{"hard":"abhorred","easy":"hated"},
{"hard":"abhorring","easy":"hating"},
{"hard":"abhors","easy":"hates"},
{"hard":"abnormal","easy":"not normal"},
{"hard":"abnormally","easy":"not normally"},
{"hard":"aboard","easy":"on"},
{"hard":"abode","easy":"living place"},
{"hard":"abolish","easy":"end"},
{"hard":"abolished","easy":"ended"},
{"hard":"abolishing","easy":"ending"},
{"hard":"abominable","easy":"very bad"},
{"hard":"abominably","easy":"very badly"},
{"hard":"abridge","easy":"shorten"},
{"hard":"abridged","easy":"shortened"},
{"hard":"abridgements","easy":"shorter forms"},
{"hard":"abridges","easy":"shortens"},
{"hard":"abridging","easy":"shortening"},
{"hard":"abridgment","easy":"shorter form"},
{"hard":"abroad","easy":"in another country"},
{"hard":"abrupt","easy":"sudden"},
{"hard":"abruptly","easy":"suddenly"},
{"hard":"absolute","easy":"complete"},
{"hard":"absolute","easy":"complete"},
{"hard":"absolutely","easy":"completely"},
{"hard":"absolutely","easy":"certainly"},
{"hard":"absolve","easy":"make free from"},
{"hard":"absolved","easy":"made free from"},
{"hard":"absorb","easy":"take up"},
{"hard":"absorbed","easy":"taken up"},
{"hard":"absorbent","easy":"able to take"},
{"hard":"absorbs","easy":"takes up"},
{"hard":"abstractly","easy":"in thoughts"},
{"hard":"absurd","easy":"strange"},
{"hard":"absurdity","easy":"strange thing"},
{"hard":"absurdly","easy":"foolishly"},
{"hard":"abuse","easy":"hurt"},
{"hard":"abused","easy":"hurt"},
{"hard":"abusive","easy":"hurtful"},
{"hard":"abysmally","easy":"very badly"},
{"hard":"academy","easy":"school"},
{"hard":"accelerate","easy":"increase in speed"},
{"hard":"accelerated","easy":"increased in speed"},
{"hard":"accelerates","easy":"increases"},
{"hard":"accelerating","easy":"increasing in speed"},
{"hard":"acceleration","easy":"increase in speed"},
{"hard":"accentuate","easy":"stress"},
{"hard":"accentuated","easy":"stressed"},
{"hard":"accentuating","easy":"stressing"},
{"hard":"accessible","easy":"usable"},
{"hard":"accommodating","easy":"nice"},
{"hard":"accommodation","easy":"room"},
{"hard":"accompanied","easy":"was with"},
{"hard":"accompanies","easy":"is with"},
{"hard":"accompany","easy":"go with"},
{"hard":"accompany","easy":"come with"},
{"hard":"accompanying","easy":"going with"},
{"hard":"accompanying","easy":"coming with"},
{"hard":"accomplice","easy":"friend"},
{"hard":"accomplish","easy":"do"},
{"hard":"accomplishes","easy":"does"},
{"hard":"accomplishing","easy":"doing"},
{"hard":"accord","easy":"agreement"},
{"hard":"accordance","easy":"agreement"},
{"hard":"accords","easy":"agreements"},
{"hard":"accost","easy":"trouble"},
{"hard":"accosted","easy":"troubled"},
{"hard":"accosting","easy":"troubling"},
{"hard":"accosts","easy":"troubles"},
{"hard":"accumulate","easy":"group"},
{"hard":"accumulated","easy":"grouped"},
{"hard":"accumulates","easy":"groups"},
{"hard":"accumulating","easy":"getting"},
{"hard":"accumulation","easy":"group"},
{"hard":"accuracy","easy":"amount of error"},
{"hard":"accurate","easy":"TRUE"},
{"hard":"accurately","easy":"correctly"},
{"hard":"accusation","easy":"claim"},
{"hard":"accusations","easy":"claims"},
{"hard":"accustomed","easy":"used to"},
{"hard":"ache","easy":"pain"},
{"hard":"ached","easy":"hurt"},
{"hard":"aches","easy":"pains"},
{"hard":"aching","easy":"hurting"},
{"hard":"acquire","easy":"get"},
{"hard":"acquired","easy":"got"},
{"hard":"acquires","easy":"gets"},
{"hard":"acquiring","easy":"getting"},
{"hard":"activate","easy":"start"},
{"hard":"activated","easy":"started"},
{"hard":"activating","easy":"starting"},
{"hard":"actual","easy":"real"},
{"hard":"actuality","easy":"fact"},
{"hard":"actually","easy":"really"},
{"hard":"acute","easy":"sharp"},
{"hard":"adage","easy":"saying"},
{"hard":"adamant","easy":"sure"},
{"hard":"adamantly","easy":"strongly"},
{"hard":"additionally","easy":"also"},
{"hard":"adept","easy":"expert"},
{"hard":"adeptly","easy":"expertly"},
{"hard":"adequate","easy":"enough"},
{"hard":"adherent","easy":"strong"},
{"hard":"adhesive","easy":"glue"},
{"hard":"adjacent","easy":"nearest"},
{"hard":"adjudicate","easy":"judge"},
{"hard":"adjudicated","easy":"judged"},
{"hard":"adjudicating","easy":"judging"},
{"hard":"adjudicator","easy":"judge"},
{"hard":"administered","easy":"gave"},
{"hard":"administers","easy":"gives"},
{"hard":"admiration","easy":"respect"},
{"hard":"admire","easy":"respect "},
{"hard":"admired","easy":"respected"},
{"hard":"admissible","easy":"allowed"},
{"hard":"admit","easy":"say"},
{"hard":"admitted","easy":"said"},
{"hard":"adolescent","easy":"child"},
{"hard":"adolescents","easy":"children"},
{"hard":"adorable","easy":"cute"},
{"hard":"adore","easy":"love"},
{"hard":"adored","easy":"loved"},
{"hard":"adoring","easy":"loving"},
{"hard":"adorn","easy":"decorate"},
{"hard":"adorned","easy":"decorated"},
{"hard":"adorning","easy":"decorating"},
{"hard":"adrift","easy":"floating"},
{"hard":"advancing","easy":"moving forward"},
{"hard":"advocated","easy":"argued"},
{"hard":"advocating","easy":"arguing"},
{"hard":"afar","easy":"far away"},
{"hard":"affable","easy":"nice"},
{"hard":"affable","easy":"kind"},
{"hard":"affection","easy":"love"},
{"hard":"affectionate","easy":"loving"},
{"hard":"affectionately","easy":"lovingly"},
{"hard":"affluent","easy":"rich"},
{"hard":"agonizing","easy":"very hard"},
{"hard":"agreeable","easy":"nice"},
{"hard":"aid","easy":"help"},
{"hard":"aint","easy":"is not"},
{"hard":"alarming","easy":"surprising"},
{"hard":"aleatoric","easy":"random"},
{"hard":"alleviate","easy":"ease"},
{"hard":"alleviated","easy":"eased"},
{"hard":"alleviating","easy":"easing"},
{"hard":"allocate","easy":"give"},
{"hard":"allocated","easy":"gave"},
{"hard":"allowing","easy":"letting"},
{"hard":"alongside","easy":"beside"},
{"hard":"ambiguous","easy":"unclear"},
{"hard":"amend","easy":"change"},
{"hard":"amiss","easy":"wrong"},
{"hard":"among","easy":"with"},
{"hard":"among","easy":"with"},
{"hard":"among","easy":"with"},
{"hard":"amputate","easy":"remove"},
{"hard":"amputated","easy":"removed"},
{"hard":"amputation","easy":"removal"},
{"hard":"amusing","easy":"funny"},
{"hard":"analogous","easy":"similar"},
{"hard":"announce","easy":"say"},
{"hard":"annual","easy":"yearly"},
{"hard":"appalled","easy":"disgusted"},
{"hard":"appalling","easy":"disgusting"},
{"hard":"apparatus","easy":"machine"},
{"hard":"appreciable","easy":"large"},
{"hard":"appreciative","easy":"thankful"},
{"hard":"apprehension","easy":"worry"},
{"hard":"apprehensive","easy":"worried"},
{"hard":"appropriate","easy":"ok"},
{"hard":"appropriated","easy":"bought "},
{"hard":"appropriating","easy":"buying"},
{"hard":"arose","easy":"grew"},
{"hard":"arouse","easy":"excite"},
{"hard":"aroused","easy":"excited"},
{"hard":"arrange","easy":"prepare"},
{"hard":"arranged","easy":"prepared"},
{"hard":"arrangements","easy":"plans"},
{"hard":"arrangements","easy":"plans"},
{"hard":"arrangements","easy":"plans"},
{"hard":"arranging","easy":"preparing"},
{"hard":"arrogance","easy":"rudeness"},
{"hard":"arrogant","easy":"rude"},
{"hard":"arrogantly","easy":"rudely"},
{"hard":"articulate","easy":"say"},
{"hard":"ascertain","easy":"find"},
{"hard":"ascertain","easy":"learn"},
{"hard":"ascertained","easy":"found"},
{"hard":"ascertaining","easy":"finding"},
{"hard":"aspects","easy":"parts"},
{"hard":"assassinate","easy":"kill"},
{"hard":"assassinated","easy":"killed"},
{"hard":"assassinating","easy":"killing"},
{"hard":"assemble","easy":"build"},
{"hard":"assembled","easy":"built"},
{"hard":"assembling","easy":"building"},
{"hard":"assist","easy":"help"},
{"hard":"assisted","easy":"helped"},
{"hard":"associate","easy":"group"},
{"hard":"associated","easy":"grouped"},
{"hard":"associating","easy":"grouping"},
{"hard":"astray","easy":"wrong"},
{"hard":"attempt","easy":"try"},
{"hard":"attempt","easy":"try"},
{"hard":"attempted","easy":"tried"},
{"hard":"attempting","easy":"trying"},
{"hard":"attempting","easy":"trying"},
{"hard":"attend","easy":"go"},
{"hard":"attended","easy":"went to"},
{"hard":"authentic","easy":"real"},
{"hard":"authentic","easy":"real"},
{"hard":"authorize","easy":"let"},
{"hard":"authorized","easy":"let"},
{"hard":"authorizing","easy":"letting"},
{"hard":"automobile","easy":"car"},
{"hard":"awful","easy":"very bad"},
{"hard":"awful","easy":"terrible"},
{"hard":"awfully","easy":"terribly"},
{"hard":"awry","easy":"wrong"},
{"hard":"banish","easy":"ban"},
{"hard":"banished","easy":"banned"},
{"hard":"barring","easy":"ignoring"},
{"hard":"based","easy":"built"},
{"hard":"bash","easy":"hit"},
{"hard":"beatific","easy":"good"},
{"hard":"began","easy":"started"},
{"hard":"begin","easy":"start"},
{"hard":"belated","easy":"late"},
{"hard":"belch","easy":"burp"},
{"hard":"belched","easy":"burped"},
{"hard":"belching","easy":"burping"},
{"hard":"bellicose","easy":"mean"},
{"hard":"bellicose","easy":"mean"},
{"hard":"belligerent","easy":"mean"},
{"hard":"belligerent","easy":"mean"},
{"hard":"belligerents","easy":"fighters"},
{"hard":"belligerents","easy":"fighters"},
{"hard":"bellow","easy":"yell"},
{"hard":"bellow","easy":"yell"},
{"hard":"belly","easy":"stomach"},
{"hard":"belongings","easy":"things"},
{"hard":"below","easy":"under"},
{"hard":"beneath","easy":"under"},
{"hard":"beneficent","easy":"good"},
{"hard":"beneficial","easy":"good"},
{"hard":"beneficial","easy":"good "},
{"hard":"benefits","easy":"helps"},
{"hard":"benevolent","easy":"good"},
{"hard":"bequeath","easy":"give "},
{"hard":"berate","easy":"criticize"},
{"hard":"berated","easy":"criticized"},
{"hard":"berating","easy":"criticizing"},
{"hard":"berserk","easy":"crazy"},
{"hard":"bestial","easy":"animal-like"},
{"hard":"bestow","easy":"give"},
{"hard":"betwixt","easy":"between"},
{"hard":"bewilder","easy":"confuse"},
{"hard":"bewildered","easy":"confused"},
{"hard":"bewildering","easy":"confusing"},
{"hard":"bicker","easy":"argue"},
{"hard":"bickered","easy":"argued"},
{"hard":"bickering","easy":"argueing"},
{"hard":"bidder","easy":"offerer"},
{"hard":"bide","easy":"wait"},
{"hard":"bids","easy":"offers"},
{"hard":"biennially","easy":"every two years"},
{"hard":"bifurcate","easy":"split"},
{"hard":"bifurcated","easy":"split"},
{"hard":"bifurcation","easy":"split"},
{"hard":"bilateral","easy":"two-sided"},
{"hard":"billiard","easy":"pool-table"},
{"hard":"bin","easy":"box"},
{"hard":"blameworthy","easy":"bad"},
{"hard":"blissful","easy":"great"},
{"hard":"bobbed","easy":"dipped"},
{"hard":"bobbing","easy":"dipping"},
{"hard":"bold","easy":"strong"},
{"hard":"boldly","easy":"strongly"},
{"hard":"bombastic","easy":"loud"},
{"hard":"bombastically","easy":"loudly"},
{"hard":"breach","easy":"break"},
{"hard":"breached","easy":"broke"},
{"hard":"briefed","easy":"taught"},
{"hard":"briefly","easy":"quickly"},
{"hard":"brink","easy":"edge"},
{"hard":"burglar","easy":"robber"},
{"hard":"burglary","easy":"robbery"},
{"hard":"burley","easy":"strong"},
{"hard":"burly","easy":"strong"},
{"hard":"bursted","easy":"broke"},
{"hard":"bursting","easy":"exploding"},
{"hard":"byproduct","easy":"result"},
{"hard":"calculate","easy":"find"},
{"hard":"cancel","easy":"stop"},
{"hard":"cancel","easy":"stop"},
{"hard":"canceled","easy":"stopped"},
{"hard":"canceling","easy":"stopping"},
{"hard":"cancelled","easy":"stopped"},
{"hard":"cancelling","easy":"stopping"},
{"hard":"capture","easy":"get"},
{"hard":"captured","easy":"got"},
{"hard":"capturing","easy":"getting"},
{"hard":"cardigan","easy":"sweater"},
{"hard":"carve","easy":"cut"},
{"hard":"carved","easy":"cut"},
{"hard":"carving","easy":"cutting"},
{"hard":"cease","easy":"end"},
{"hard":"ceased","easy":"ended"},
{"hard":"ceaseless","easy":"endless"},
{"hard":"challenging","easy":"difficult"},
{"hard":"chapter","easy":"part"},
{"hard":"chastise","easy":"criticize"},
{"hard":"chastising","easy":"criticizing"},
{"hard":"cheerful","easy":"happy"},
{"hard":"cheery","easy":"happy"},
{"hard":"cherish","easy":"love"},
{"hard":"cherished","easy":"loved"},
{"hard":"cherishing","easy":"loving"},
{"hard":"chesterfield","easy":"couch"},
{"hard":"chop","easy":"cut"},
{"hard":"chopped","easy":"cut"},
{"hard":"chopping","easy":"making cuts"},
{"hard":"choppy","easy":"rough"},
{"hard":"chuckle","easy":"laugh"},
{"hard":"chuckled","easy":"laughed"},
{"hard":"chuckling","easy":"laughing"},
{"hard":"circumstance","easy":"situation"},
{"hard":"circumstance","easy":"situation"},
{"hard":"circumstance","easy":"situation"},
{"hard":"circumvent","easy":"get around"},
{"hard":"circumvented","easy":"got around"},
{"hard":"circumventing","easy":"getting around"},
{"hard":"circumvents","easy":"gets around"},
{"hard":"civilizations","easy":"societies"},
{"hard":"clad","easy":"clothed"},
{"hard":"clamber","easy":"climb"},
{"hard":"clambering","easy":"climbing"},
{"hard":"clarifies","easy":"clears"},
{"hard":"clarify","easy":"clear"},
{"hard":"clarifying","easy":"clearing"},
{"hard":"clasp","easy":"grip"},
{"hard":"cleaver","easy":"knife"},
{"hard":"cleft","easy":"crack"},
{"hard":"cling","easy":"hold"},
{"hard":"clinging","easy":"holding"},
{"hard":"clique","easy":"group"},
{"hard":"clone","easy":"copy"},
{"hard":"coalesce","easy":"form"},
{"hard":"coalesced","easy":"formed"},
{"hard":"coalescing","easy":"forming"},
{"hard":"cobbler","easy":"shoe maker"},
{"hard":"coerce","easy":"force"},
{"hard":"coined","easy":"created"},
{"hard":"collaborate","easy":"work together"},
{"hard":"collate","easy":"organize"},
{"hard":"collide","easy":"hit"},
{"hard":"collided","easy":"hit"},
{"hard":"collides","easy":"hits"},
{"hard":"colliding","easy":"hitting"},
{"hard":"colloquial","easy":"everyday"},
{"hard":"colossal","easy":"big"},
{"hard":"combining","easy":"mixing"},
{"hard":"comforter","easy":"blanket"},
{"hard":"comfy","easy":"comfortable"},
{"hard":"comical","easy":"funny"},
{"hard":"commence","easy":"start"},
{"hard":"commitment","easy":"promise"},
{"hard":"common","easy":"normal"},
{"hard":"commonly","easy":"normally"},
{"hard":"communal","easy":"group"},
{"hard":"commute","easy":"travel"},
{"hard":"commute","easy":"travel"},
{"hard":"commuted","easy":"traveled"},
{"hard":"commuted","easy":"traveled"},
{"hard":"commuter","easy":"traveler"},
{"hard":"commuter","easy":"traveler"},
{"hard":"commuting","easy":"traveling"},
{"hard":"commuting","easy":"traveling"},
{"hard":"companion","easy":"friend"},
{"hard":"compel","easy":"force"},
{"hard":"compelled","easy":"forced"},
{"hard":"compelling","easy":"strong"},
{"hard":"compilation","easy":"collection"},
{"hard":"complaisant","easy":"nice"},
{"hard":"compliance","easy":"agreement "},
{"hard":"compliant","easy":"agreeable"},
{"hard":"complimentary","easy":"free"},
{"hard":"comply","easy":"agree"},
{"hard":"component","easy":"part"},
{"hard":"components","easy":"parts"},
{"hard":"compose","easy":"make"},
{"hard":"compose","easy":"make"},
{"hard":"composed","easy":"made"},
{"hard":"composed","easy":"made"},
{"hard":"composing","easy":"making"},
{"hard":"comprehend","easy":"understand"},
{"hard":"comprehension","easy":"understanding"},
{"hard":"comprehensive","easy":"complete"},
{"hard":"compressed","easy":"squeezed"},
{"hard":"compressing","easy":"squeezing"},
{"hard":"comprised","easy":"made"},
{"hard":"compulsory","easy":"necessary"},
{"hard":"concatenate","easy":"join"},
{"hard":"conceal","easy":"hide"},
{"hard":"conceal","easy":"hide"},
{"hard":"concealed","easy":"hidden"},
{"hard":"concealed","easy":"hid"},
{"hard":"concealing","easy":"hiding"},
{"hard":"concealing","easy":"hiding"},
{"hard":"conception","easy":"understanding"},
{"hard":"concern","easy":"worry"},
{"hard":"concerned","easy":"worried"},
{"hard":"concerning","easy":"about"},
{"hard":"concoct","easy":"make"},
{"hard":"concocted","easy":"made"},
{"hard":"concocting","easy":"creating"},
{"hard":"concurrent","easy":"simultaneous"},
{"hard":"condone","easy":"support"},
{"hard":"condoned","easy":"supported"},
{"hard":"condoning","easy":"supporting"},
{"hard":"confidential","easy":"secret"},
{"hard":"confidentiality","easy":"secretly"},
{"hard":"confiscate","easy":"take"},
{"hard":"confiscated","easy":"taken"},
{"hard":"confiscating","easy":"taking"},
{"hard":"conform","easy":"agree"},
{"hard":"conforming","easy":"aggreeing"},
{"hard":"congeal","easy":"solidify"},
{"hard":"congealed","easy":"solidified"},
{"hard":"congealing","easy":"solidifying"},
{"hard":"conglomeration","easy":"mass"},
{"hard":"conglomeration","easy":"organization"},
{"hard":"congregate","easy":"come together"},
{"hard":"consensus","easy":"general agreement"},
{"hard":"consensus","easy":"agreement"},
{"hard":"consenting","easy":"agreeing"},
{"hard":"consequence","easy":"effect"},
{"hard":"consider","easy":"think about"},
{"hard":"considerable","easy":"big"},
{"hard":"considerable","easy":"much"},
{"hard":"considerably","easy":"very"},
{"hard":"considerate","easy":"thoughtful"},
{"hard":"considerate","easy":"nice"},
{"hard":"consideration","easy":"thought"},
{"hard":"consise","easy":"neat"},
{"hard":"constituent","easy":"inner"},
{"hard":"construct","easy":"make"},
{"hard":"construct","easy":"build"},
{"hard":"constructed","easy":"made"},
{"hard":"constructed","easy":"built"},
{"hard":"constructing","easy":"making"},
{"hard":"constructing","easy":"building"},
{"hard":"construction","easy":"building"},
{"hard":"constructive","easy":"helping"},
{"hard":"consume","easy":"eat"},
{"hard":"containing","easy":"having"},
{"hard":"contains","easy":"has"},
{"hard":"contains","easy":"has"},
{"hard":"contemporary","easy":"recent"},
{"hard":"contented","easy":"happy"},
{"hard":"continually","easy":"constantly"},
{"hard":"continuous","easy":"unbroken"},
{"hard":"contour","easy":"outline"},
{"hard":"contra","easy":"against"},
{"hard":"contraption","easy":"machine"},
{"hard":"contributed","easy":"gave"},
{"hard":"contributing","easy":"giving"},
{"hard":"contributor","easy":"giver"},
{"hard":"conventional","easy":"normal"},
{"hard":"conventionally","easy":"normally"},
{"hard":"converge","easy":"come together"},
{"hard":"converged","easy":"came together"},
{"hard":"converging","easy":"coming together"},
{"hard":"conversion","easy":"change"},
{"hard":"conversion","easy":"change"},
{"hard":"conversion","easy":"change"},
{"hard":"converted","easy":"changed"},
{"hard":"converted","easy":"changed"},
{"hard":"converted","easy":"changed"},
{"hard":"converted","easy":"changed"},
{"hard":"converting","easy":"changing"},
{"hard":"converting","easy":"changing"},
{"hard":"convocated","easy":"graduated"},
{"hard":"convocation","easy":"graduation"},
{"hard":"cools","easy":"gets colder"},
{"hard":"cop","easy":"police officer"},
{"hard":"copious","easy":"large"},
{"hard":"cordial","easy":"nice"},
{"hard":"corporate","easy":"business"},
{"hard":"corpse","easy":"dead body"},
{"hard":"corpses","easy":"dead bodies"},
{"hard":"corpulent","easy":"fat"},
{"hard":"corrected","easy":"fixed"},
{"hard":"corridor","easy":"hall"},
{"hard":"corridor","easy":"hall"},
{"hard":"costly","easy":"expensive"},
{"hard":"couldâve","easy":"could have"},
{"hard":"couldn't","easy":"could not"},
{"hard":"counterfactual","easy":"wrong"},
{"hard":"counterfeit","easy":"fake"},
{"hard":"courteous","easy":"polite"},
{"hard":"courteous","easy":"nice"},
{"hard":"courteous","easy":"nice"},
{"hard":"courteously","easy":"politely"},
{"hard":"covenant","easy":"promise"},
{"hard":"cozy","easy":"comfortable"},
{"hard":"crabby","easy":"rude"},
{"hard":"cracked in","easy":"fixing"},
{"hard":"crafted","easy":"made"},
{"hard":"crafted","easy":"made"},
{"hard":"crafting","easy":"making"},
{"hard":"crafting","easy":"making"},
{"hard":"crafty","easy":"smart"},
{"hard":"crashed","easy":"smashed"},
{"hard":"crashing","easy":"smashing"},
{"hard":"crass","easy":"rude"},
{"hard":"crave","easy":"want"},
{"hard":"craved","easy":"wanted"},
{"hard":"craving","easy":"wanting"},
{"hard":"created","easy":"made"},
{"hard":"creating","easy":"making"},
{"hard":"crowded","easy":"filled"},
{"hard":"crucial","easy":"important"},
{"hard":"crucial","easy":"very important"},
{"hard":"crucial","easy":"important"},
{"hard":"crucially","easy":"importantly"},
{"hard":"crucially","easy":"importantly "},
{"hard":"cruel","easy":"mean"},
{"hard":"cruel","easy":"mean"},
{"hard":"cruised","easy":"drove"},
{"hard":"cruising","easy":"driving"},
{"hard":"crumple","easy":"crush"},
{"hard":"cumbersome","easy":"difficult"},
{"hard":"currency","easy":"money"},
{"hard":"cursory","easy":"quick"},
{"hard":"curt","easy":"short"},
{"hard":"customary","easy":"normal"},
{"hard":"cyber","easy":"internet"},
{"hard":"cyberspace","easy":"internet"},
{"hard":"cycle","easy":"circle"},
{"hard":"cycled","easy":"circled"},
{"hard":"dagger","easy":"knife"},
{"hard":"dagger","easy":"knife"},
{"hard":"dainty","easy":"delicate "},
{"hard":"damnable","easy":"bad"},
{"hard":"dandy","easy":"nice"},
{"hard":"dangle","easy":"hang"},
{"hard":"dangled","easy":"hanging"},
{"hard":"dangling","easy":"hanging"},
{"hard":"dazzle","easy":"impress"},
{"hard":"dazzled","easy":"impressed"},
{"hard":"debris","easy":"broken parts"},
{"hard":"decade","easy":"ten years"},
{"hard":"decades","easy":"tens of years"},
{"hard":"deceased","easy":"dead"},
{"hard":"deciding","easy":"choosing"},
{"hard":"declaration","easy":"statement"},
{"hard":"declarations","easy":"statements"},
{"hard":"decompose","easy":"breakdown"},
{"hard":"decomposing","easy":"breaking down"},
{"hard":"decoy","easy":"fake"},
{"hard":"decreased","easy":"lowered"},
{"hard":"decreases","easy":"lowers"},
{"hard":"decreasing","easy":"lowering"},
{"hard":"decreasing","easy":"lowering"},
{"hard":"decrepit","easy":"broken"},
{"hard":"deduct","easy":"remove"},
{"hard":"deduct","easy":"take away "},
{"hard":"deducted","easy":"removed"},
{"hard":"deducting","easy":"taking away"},
{"hard":"deducting","easy":"removing"},
{"hard":"deem","easy":"declare"},
{"hard":"deemed","easy":"declared"},
{"hard":"defective","easy":"bad"},
{"hard":"deference","easy":"respect"},
{"hard":"deference","easy":"respect"},
{"hard":"deferential","easy":"nice"},
{"hard":"defiled","easy":"dirtied"},
{"hard":"definite","easy":"sure"},
{"hard":"degenerated","easy":"broke down"},
{"hard":"degenerating","easy":"breaking"},
{"hard":"deliberately","easy":"purposely"},
{"hard":"delicate","easy":"special"},
{"hard":"delighted","easy":"happy"},
{"hard":"delighted","easy":"nice"},
{"hard":"demeanor","easy":"behavior"},
{"hard":"demeanour","easy":"behaviour"},
{"hard":"demolish","easy":"destroy"},
{"hard":"demolish","easy":"destroy"},
{"hard":"demolished","easy":"destroyed"},
{"hard":"demolished","easy":"destroyed"},
{"hard":"demolishes","easy":"destroys"},
{"hard":"demolishing","easy":"destroying"},
{"hard":"demolishing","easy":"destroying"},
{"hard":"demonstrate","easy":"show"},
{"hard":"demonstrated","easy":"shown"},
{"hard":"demonstrating","easy":"showing"},
{"hard":"dense","easy":"full"},
{"hard":"depart","easy":"leave"},
{"hard":"departing","easy":"leaving"},
{"hard":"depict","easy":"show"},
{"hard":"depicted","easy":"shown"},
{"hard":"depicting","easy":"showing"},
{"hard":"deplorable","easy":"terrible"},
{"hard":"deplorable","easy":"terrible"},
{"hard":"depressed","easy":"sad"},
{"hard":"depression","easy":"sadness"},
{"hard":"deride","easy":"make fun of"},
{"hard":"derision","easy":"disrespect"},
{"hard":"derisively","easy":"meanly"},
{"hard":"derogatory","easy":"mean"},
{"hard":"desire","easy":"want"},
{"hard":"desired","easy":"wanted"},
{"hard":"desiring","easy":"wanting"},
{"hard":"despair","easy":"worry"},
{"hard":"despairing","easy":"worrying "},
{"hard":"despicable","easy":"terrible"},
{"hard":"despicable","easy":"terrible"},
{"hard":"despicable","easy":"disgusting"},
{"hard":"deteriorate","easy":"break"},
{"hard":"detestable","easy":"terrible"},
{"hard":"detrimental","easy":"bad"},
{"hard":"device","easy":"tool"},
{"hard":"devilish","easy":"very bad"},
{"hard":"devise","easy":"make"},
{"hard":"devised","easy":"made"},
{"hard":"devising","easy":"making"},
{"hard":"devising","easy":"making"},
{"hard":"devotion","easy":"respect"},
{"hard":"devout","easy":"serious"},
{"hard":"diminish","easy":"lessen"},
{"hard":"diminished","easy":"lowered"},
{"hard":"diminishing","easy":"lessening"},
{"hard":"dire","easy":"bad"},
{"hard":"disastrous","easy":"and very bad"},
{"hard":"discard","easy":"drop"},
{"hard":"disclose","easy":"tell"},
{"hard":"disclose","easy":"tell"},
{"hard":"disclosed","easy":"told"},
{"hard":"disclosing","easy":"telling"},
{"hard":"discontinue","easy":"stop"},
{"hard":"discontinued","easy":"stopped"},
{"hard":"discretion","easy":"decision"},
{"hard":"discuss","easy":"talk about"},
{"hard":"discussed","easy":"talked about"},
{"hard":"discusses","easy":"talks about"},
{"hard":"disembark","easy":"leave"},
{"hard":"disembarked","easy":"left"},
{"hard":"disembarking","easy":"leaving"},
{"hard":"disgraceful","easy":"bad"},
{"hard":"disgusting","easy":"terrible"},
{"hard":"dismal","easy":"sad"},
{"hard":"disparaged","easy":"insulted"},
{"hard":"disparagement","easy":"insult"},
{"hard":"disparaging","easy":"insulting"},
{"hard":"dispiriting","easy":"sad"},
{"hard":"display","easy":"show"},
{"hard":"displayed","easy":"showed"},
{"hard":"displaying","easy":"showing"},
{"hard":"disregarded","easy":"ignored"},
{"hard":"disregarding","easy":"ignoring"},
{"hard":"dissemination","easy":"sharing"},
{"hard":"distinguish","easy":"separate"},
{"hard":"distinguishing","easy":"separating"},
{"hard":"donate","easy":"give"},
{"hard":"donated","easy":"gave"},
{"hard":"donating","easy":"giving"},
{"hard":"drastic","easy":"extreme"},
{"hard":"drastic","easy":"dramatic"},
{"hard":"drastically","easy":"dramatically"},
{"hard":"dread","easy":"fear"},
{"hard":"dreaded","easy":"feared"},
{"hard":"dreadful","easy":"terrible"},
{"hard":"dreadful","easy":"terrible"},
{"hard":"dreading","easy":"fearing"},
{"hard":"dreary","easy":"unhappy"},
{"hard":"duration","easy":"length"},
{"hard":"duty","easy":"job"},
{"hard":"duvet","easy":"blanket"},
{"hard":"eager","easy":"excited"},
{"hard":"edit","easy":"change"},
{"hard":"educating","easy":"teaching"},
{"hard":"eject","easy":"remove"},
{"hard":"ejected","easy":"removed"},
{"hard":"ejecting","easy":"removing"},
{"hard":"elated","easy":"excited"},
{"hard":"elegant","easy":"nice"},
{"hard":"elegantly","easy":"nicely"},
{"hard":"elemental","easy":"basic"},
{"hard":"elementary","easy":"basic"},
{"hard":"elementary","easy":"basic"},
{"hard":"eliminate","easy":"remove"},
{"hard":"eliminated","easy":"removed"},
{"hard":"eliminating","easy":"removing"},
{"hard":"elimination","easy":"removal"},
{"hard":"eliminator","easy":"remover"},
{"hard":"elongate","easy":"stretch"},
{"hard":"elongated","easy":"stretched"},
{"hard":"elongating","easy":"stretching"},
{"hard":"eloquent","easy":"smooth"},
{"hard":"eloquently","easy":"smoothly"},
{"hard":"emmigrate","easy":"move"},
{"hard":"empathic","easy":"strong"},
{"hard":"emphatically","easy":"heavily"},
{"hard":"employee","easy":"worker"},
{"hard":"enable","easy":"let"},
{"hard":"enabled","easy":"let"},
{"hard":"enabling","easy":"letting"},
{"hard":"enigma","easy":"mystery"},
{"hard":"ennui","easy":"boredom"},
{"hard":"enormous","easy":"very big"},
{"hard":"enrich","easy":"improve"},
{"hard":"enriched","easy":"improved"},
{"hard":"enthusiasm","easy":"excitement"},
{"hard":"enthusiastic","easy":"excited"},
{"hard":"entire","easy":"whole"},
{"hard":"entirely","easy":"very"},
{"hard":"entirely","easy":"completely"},
{"hard":"entrenched","easy":"stuck"},
{"hard":"envisage","easy":"see"},
{"hard":"equipped","easy":"prepared"},
{"hard":"eradicate","easy":"remove"},
{"hard":"eradicated","easy":"removed"},
{"hard":"eradicating","easy":"removing"},
{"hard":"escalate","easy":"increase"},
{"hard":"escalated","easy":"increased"},
{"hard":"escalating","easy":"growing"},
{"hard":"establish","easy":"make"},
{"hard":"established","easy":"made"},
{"hard":"establishing","easy":"making"},
{"hard":"esteem","easy":"respect"},
{"hard":"estimate","easy":"guess"},
{"hard":"estimated","easy":"guessed"},
{"hard":"evacuate","easy":"empty"},
{"hard":"evacuated","easy":"emptied"},
{"hard":"evacuating","easy":"leaving"},
{"hard":"evade","easy":"avoid"},
{"hard":"evening","easy":"night"},
{"hard":"exasperate","easy":"tire"},
{"hard":"exasperated","easy":"tired"},
{"hard":"exasperating","easy":"tiring"},
{"hard":"exceed","easy":"pass"},
{"hard":"exceeds","easy":"passes"},
{"hard":"excellence","easy":"greatness"},
{"hard":"excellent","easy":"great"},
{"hard":"excellent","easy":"very good"},
{"hard":"exceptionally","easy":"very"},
{"hard":"exchanged","easy":"traded"},
{"hard":"exchanged","easy":"traded"},
{"hard":"exchanging","easy":"trading"},
{"hard":"exchanging","easy":"trading"},
{"hard":"exclude","easy":"leave out"},
{"hard":"excluded","easy":"left out"},
{"hard":"excludes","easy":"leaves out"},
{"hard":"excluding","easy":"leaving out"},
{"hard":"exclusively","easy":"only"},
{"hard":"excrement","easy":"poo"},
{"hard":"excursion","easy":"trip"},
{"hard":"exemplary","easy":"excellent"},
{"hard":"exemplary","easy":"great"},
{"hard":"exemplary","easy":"great"},
{"hard":"exhausted","easy":"very tired"},
{"hard":"exhausting","easy":"very tiring"},
{"hard":"expand","easy":"grow"},
{"hard":"expanded","easy":"grew"},
{"hard":"expanding","easy":"growing"},
{"hard":"expressed","easy":"said"},
{"hard":"expressing","easy":"saying"},
{"hard":"exquisite","easy":"very nice"},
{"hard":"extend","easy":"grow"},
{"hard":"extensive","easy":"big"},
{"hard":"extent","easy":"amount"},
{"hard":"extinguish","easy":"stop"},
{"hard":"extinguished","easy":"stopped"},
{"hard":"fabricate","easy":"make up"},
{"hard":"fabricated","easy":"made up"},
{"hard":"fabricates","easy":"makes up"},
{"hard":"fabrication","easy":"fiction"},
{"hard":"facetiously","easy":"jokingly"},
{"hard":"facilitate","easy":"help"},
{"hard":"facilitated","easy":"helped"},
{"hard":"facilitating","easy":"helping"},
{"hard":"failing to have","easy":"organizing"},
{"hard":"fallacious","easy":"wrong"},
{"hard":"fancy","easy":"special"},
{"hard":"fantastic","easy":"amazing"},
{"hard":"fantastically","easy":"amazingly"},
{"hard":"fare","easy":"price"},
{"hard":"fared","easy":"did"},
{"hard":"faring","easy":"doing"},
{"hard":"fascinate","easy":"interest"},
{"hard":"fascinating","easy":"interesting"},
{"hard":"fasten","easy":"lock"},
{"hard":"fathom","easy":"understand"},
{"hard":"fatigued","easy":"tired"},
{"hard":"fatiguing","easy":"tiring"},
{"hard":"faulty","easy":"broken"},
{"hard":"favored","easy":"liked"},
{"hard":"favoring","easy":"liking"},
{"hard":"favourable","easy":"good"},
{"hard":"favoured","easy":"liked"},
{"hard":"favouring","easy":"liking"},
{"hard":"feeble","easy":"weak"},
{"hard":"fend","easy":"fight"},
{"hard":"fended","easy":"fought"},
{"hard":"fending","easy":"fighting"},
{"hard":"festive","easy":"happy"},
{"hard":"fevered","easy":"excited"},
{"hard":"fiendish","easy":"bad"},
{"hard":"final","easy":"last"},
{"hard":"financed","easy":"paid for"},
{"hard":"fixated","easy":"obsessed"},
{"hard":"fixation","easy":"obsession"},
{"hard":"flourish","easy":"grow"},
{"hard":"flourishing","easy":"growing"},
{"hard":"folks","easy":"people"},
{"hard":"fooled","easy":"tricked"},
{"hard":"fooling","easy":"tricking"},
{"hard":"forging","easy":"making"},
{"hard":"forked","easy":"split"},
{"hard":"forking","easy":"splitting"},
{"hard":"formal","easy":"nice"},
{"hard":"formal","easy":"important"},
{"hard":"formulate","easy":"make"},
{"hard":"formulated","easy":"made"},
{"hard":"formulating","easy":"making"},
{"hard":"fortunately","easy":"luckily"},
{"hard":"foundational","easy":"basic"},
{"hard":"frankly","easy":"basically"},
{"hard":"frantic","easy":"excited"},
{"hard":"frantic","easy":"crazy"},
{"hard":"frantically","easy":"almost"},
{"hard":"fraternal","easy":"brotherly"},
{"hard":"fraternity","easy":"club"},
{"hard":"fraudulent","easy":"fake"},
{"hard":"frenetic","easy":"excited"},
{"hard":"frenzied","easy":"excited"},
{"hard":"frenzied","easy":"crazy"},
{"hard":"frequently","easy":"often"},
{"hard":"frolic","easy":"play"},
{"hard":"frontier","easy":"edge"},
{"hard":"functioning","easy":"working"},
{"hard":"fundamental","easy":"basic"},
{"hard":"funded","easy":"paid for"},
{"hard":"funding","easy":"money"},
{"hard":"funds","easy":"money"},
{"hard":"furious","easy":"very angry"},
{"hard":"furiously","easy":"violently"},
{"hard":"furnace","easy":"heater"},
{"hard":"fury","easy":"violence"},
{"hard":"futile","easy":"useless"},
{"hard":"gabbed","easy":"talked"},
{"hard":"gabbing","easy":"talking"},
{"hard":"gal","easy":"girl"},
{"hard":"gal","easy":"girl "},
{"hard":"gamble","easy":"bet"},
{"hard":"gambled","easy":"bet"},
{"hard":"garment","easy":"clothing"},
{"hard":"gaze","easy":"look"},
{"hard":"gazed","easy":"looked"},
{"hard":"gazing","easy":"looking"},
{"hard":"generate","easy":"make"},
{"hard":"generated","easy":"made"},
{"hard":"generating","easy":"making"},
{"hard":"genial","easy":"warm of heart"},
{"hard":"genteel","easy":"nice"},
{"hard":"gentle","easy":"careful"},
{"hard":"gently","easy":"carefully"},
{"hard":"genuine","easy":"real"},
{"hard":"genuinely","easy":"truly"},
{"hard":"get-go","easy":"beginning "},
{"hard":"giddy","easy":"excited"},
{"hard":"gigantic","easy":"very big"},
{"hard":"gigantic","easy":"very big"},
{"hard":"giggle","easy":"laugh"},
{"hard":"giggled","easy":"laughed"},
{"hard":"giggling","easy":"laughing"},
{"hard":"glad","easy":"happy"},
{"hard":"glean","easy":"take"},
{"hard":"gleaned","easy":"taken"},
{"hard":"glimpse","easy":"quick look"},
{"hard":"glitch","easy":"problem"},
{"hard":"glitches","easy":"problems"},
{"hard":"gloomy","easy":"sad"},
{"hard":"glum","easy":"sad"},
{"hard":"gonna","easy":"going to"},
{"hard":"gracefully","easy":"nicely"},
{"hard":"gracious","easy":"thankful"},
{"hard":"gradual","easy":"slow"},
{"hard":"gradual","easy":"slow"},
{"hard":"gradually","easy":"slowly"},
{"hard":"gradually","easy":"slowly"},
{"hard":"granting","easy":"giving"},
{"hard":"grateful","easy":"thankful"},
{"hard":"gratis","easy":"free"},
{"hard":"grievance","easy":"complaint"},
{"hard":"grievous","easy":"terrible"},
{"hard":"grim","easy":"bad"},
{"hard":"grin","easy":"smile"},
{"hard":"grinned","easy":"smiled"},
{"hard":"grinning","easy":"smiling"},
{"hard":"grip","easy":"hold"},
{"hard":"groceries","easy":"food"},
{"hard":"grubby","easy":"dirty"},
{"hard":"gruesome","easy":"terrible"},
{"hard":"guffaw","easy":"laugh"},
{"hard":"guffawed","easy":"laughed"},
{"hard":"guided","easy":"led"},
{"hard":"guided","easy":"led"},
{"hard":"gullet","easy":"throat"},
{"hard":"gusto","easy":"great pleasure"},
{"hard":"guy","easy":"man"},
{"hard":"guys","easy":"men"},
{"hard":"halt","easy":"stop"},
{"hard":"halted","easy":"stopped"},
{"hard":"halting","easy":"stopping"},
{"hard":"hands-down","easy":"definitely "},
{"hard":"hardiest","easy":"strongest"},
{"hard":"hardly","easy":"barely"},
{"hard":"hardy","easy":"strong"},
{"hard":"harm","easy":"trouble"},
{"hard":"harmed","easy":"hurt"},
{"hard":"harming","easy":"hurting"},
{"hard":"hath","easy":"has"},
{"hard":"haute","easy":"high"},
{"hard":"havoc","easy":"chaos"},
{"hard":"haywire","easy":"crazy"},
{"hard":"hazard","easy":"danger"},
{"hard":"hazardous","easy":"dangerous"},
{"hard":"heartless","easy":"unkind"},
{"hard":"heed","easy":"attention"},
{"hard":"hefty","easy":"large"},
{"hard":"hefty","easy":"strong"},
{"hard":"heinous","easy":"terrible"},
{"hard":"henceforth","easy":"from now on"},
{"hard":"henceforth","easy":"from now on"},
{"hard":"hideous","easy":"terrible"},
{"hard":"hideously","easy":"terriblly"},
{"hard":"highly","easy":"very"},
{"hard":"hike","easy":"walk"},
{"hard":"hiked","easy":"walked"},
{"hard":"hiking","easy":"walking"},
{"hard":"hitherto","easy":"untill now"},
{"hard":"hitherto","easy":"until now"},
{"hard":"hobbies","easy":"interests"},
{"hard":"hobby","easy":"interest"},
{"hard":"hoisted","easy":"lifted"},
{"hard":"hoisting","easy":"lifting"},
{"hard":"honor","easy":"respect"},
{"hard":"honored","easy":"respected"},
{"hard":"honoured","easy":"respected"},
{"hard":"horrendous","easy":"terrible"},
{"hard":"horrendously","easy":"terribly"},
{"hard":"horrible","easy":"terrible"},
{"hard":"horrid","easy":"terrible"},
{"hard":"horrific","easy":"terrible"},
{"hard":"horrified","easy":"terrified"},
{"hard":"horrifying","easy":"terrible"},
{"hard":"hound","easy":"dog"},
{"hard":"howâd","easy":"how did"},
{"hard":"howl","easy":"yell"},
{"hard":"humane","easy":"kind"},
{"hard":"humble","easy":"simple"},
{"hard":"humiliate","easy":"embarrass"},
{"hard":"humiliated","easy":"embarrassed"},
{"hard":"humor","easy":"comedy"},
{"hard":"humorous","easy":"funny"},
{"hard":"humour","easy":"comedy"},
{"hard":"hymn","easy":"song"},
{"hard":"hypothesis","easy":"guess"},
{"hard":"hypothesize","easy":"guess"},
{"hard":"i'll","easy":"I will"},
{"hard":"i'll","easy":"I will"},
{"hard":"i've","easy":"I have"},
{"hard":"illegality","easy":"crime"},
{"hard":"illuminated","easy":"lit"},
{"hard":"illustrating","easy":"drawing"},
{"hard":"illustration","easy":"picture"},
{"hard":"image","easy":"picture"},
{"hard":"immaculate","easy":"perfect"},
{"hard":"immediately","easy":"very soon"},
{"hard":"immense","easy":"very big"},
{"hard":"immigrate","easy":"move"},
{"hard":"immoral","easy":"bad"},
{"hard":"impart","easy":"give "},
{"hard":"impart","easy":"teach"},
{"hard":"imparted","easy":"tought"},
{"hard":"imparted","easy":"gave"},
{"hard":"imparting","easy":"teaching"},
{"hard":"imparting","easy":"giving"},
{"hard":"impeccable","easy":"perfect"},
{"hard":"impeccably","easy":"perfectly"},
{"hard":"impelled","easy":"forced"},
{"hard":"impending","easy":"nearing"},
{"hard":"improper","easy":"bad"},
{"hard":"impropriety","easy":"crime"},
{"hard":"inaccurate","easy":"wrong"},
{"hard":"inaccurate","easy":"wrong"},
{"hard":"inadequacies","easy":"problems"},
{"hard":"inane","easy":"stupid"},
{"hard":"inapropriate","easy":"not ok"},
{"hard":"inception","easy":"beginning"},
{"hard":"incoherent","easy":"senseless"},
{"hard":"incompetent","easy":"stupid"},
{"hard":"incorrect","easy":"wrong"},
{"hard":"increase","easy":"raise"},
{"hard":"increasing","easy":"raising"},
{"hard":"indicate","easy":"show"},
{"hard":"indicate","easy":"show"},
{"hard":"indicated","easy":"showed"},
{"hard":"indicated","easy":"showed"},
{"hard":"indicating","easy":"showing"},
{"hard":"indicating","easy":"showing"},
{"hard":"industry","easy":"business"},
{"hard":"inebriated","easy":"drunk"},
{"hard":"inexpensive","easy":"cheap"},
{"hard":"inexpressible","easy":"unsayable"},
{"hard":"infant","easy":"baby"},
{"hard":"infants","easy":"babies"},
{"hard":"inferior","easy":"poor"},
{"hard":"infinitesimal","easy":"very small"},
{"hard":"inform","easy":"tell"},
{"hard":"inform","easy":"tell"},
{"hard":"informed","easy":"told"},
{"hard":"informing","easy":"telling"},
{"hard":"informing","easy":"telling"},
{"hard":"infuriate","easy":"anger"},
{"hard":"infuriated","easy":"angry"},
{"hard":"ingenious","easy":"smart"},
{"hard":"ingenious","easy":"smart"},
{"hard":"ingest","easy":"eat"},
{"hard":"ingested","easy":"ate"},
{"hard":"ingesting","easy":"eating"},
{"hard":"inhabit","easy":"live in"},
{"hard":"inhabit","easy":"live in"},
{"hard":"inhabited","easy":"lived in"},
{"hard":"inhabiting","easy":"living in"},
{"hard":"initial","easy":"first"},
{"hard":"initialisation","easy":"preparation"},
{"hard":"initialise","easy":"prepare"},
{"hard":"initialised","easy":"prepared"},
{"hard":"initialising","easy":"preparing"},
{"hard":"initialization","easy":"preparation"},
{"hard":"initialize","easy":"prepare"},
{"hard":"initialized","easy":"prepared"},
{"hard":"initializing","easy":"preparing"},
{"hard":"initially","easy":"at first"},
{"hard":"initiate","easy":"start"},
{"hard":"initiated","easy":"started"},
{"hard":"initiating","easy":"starting"},
{"hard":"inject","easy":"put"},
{"hard":"injure","easy":"hurt"},
{"hard":"injure","easy":"hurt"},
{"hard":"injured","easy":"hurt"},
{"hard":"injured","easy":"hurt"},
{"hard":"injuring","easy":"hurting"},
{"hard":"injuring","easy":"hurting"},
{"hard":"inquire","easy":"ask"},
{"hard":"inquired","easy":"asked"},
{"hard":"inquiring","easy":"asking"},
{"hard":"inquiry","easy":"question"},
{"hard":"insane","easy":"crazy"},
{"hard":"insanity","easy":"craziness"},
{"hard":"inscribe","easy":"write"},
{"hard":"inscribing","easy":"writing"},
{"hard":"inserted","easy":"put"},
{"hard":"inserting","easy":"putting"},
{"hard":"insinuated","easy":"suggested"},
{"hard":"insinuating","easy":"suggesting"},
{"hard":"inspire","easy":"excite"},
{"hard":"inspire","easy":"excite"},
{"hard":"inspired","easy":"excited"},
{"hard":"inspired","easy":"excited"},
{"hard":"inspiring","easy":"exciting"},
{"hard":"instigate","easy":"excite"},
{"hard":"instigated","easy":"excited"},
{"hard":"instruct","easy":"teach"},
{"hard":"instructed","easy":"taught"},
{"hard":"instructing","easy":"teaching"},
{"hard":"instructor","easy":"teacher"},
{"hard":"instrumentation","easy":"tools"},
{"hard":"insurgency","easy":"rebellion"},
{"hard":"insurgent","easy":"rebel"},
{"hard":"intact","easy":"complete"},
{"hard":"integer","easy":"whole number"},
{"hard":"intelligent","easy":"smart"},
{"hard":"intend","easy":"plan"},
{"hard":"intending","easy":"planning"},
{"hard":"intense","easy":"very strong"},
{"hard":"intensely","easy":"strongly"},
{"hard":"intensity","easy":"strength"},
{"hard":"interim","easy":"temporary"},
{"hard":"interlaced","easy":"twisted"},
{"hard":"interlacing","easy":"twisting"},
{"hard":"internals","easy":"insides"},
{"hard":"interrogate","easy":"question"},
{"hard":"interrogated","easy":"questioned"},
{"hard":"interrogating","easy":"questioning"},
{"hard":"interrogation","easy":"questioning"},
{"hard":"intersect","easy":"cross"},
{"hard":"intersected","easy":"crossed"},
{"hard":"intersecting","easy":"crossing"},
{"hard":"intersperse","easy":"spread"},
{"hard":"interspersed","easy":"spread"},
{"hard":"interspersing","easy":"spreading"},
{"hard":"intricate","easy":"complex"},
{"hard":"intrigued","easy":"interested"},
{"hard":"intriguing","easy":"interesting"},
{"hard":"introspective","easy":"thoughtful"},
{"hard":"inundate","easy":"fill"},
{"hard":"inundated","easy":"filled"},
{"hard":"invariably","easy":"always"},
{"hard":"invariably","easy":"always"},
{"hard":"invariably","easy":"always"},
{"hard":"invent","easy":"create"},
{"hard":"invent","easy":"create"},
{"hard":"invented","easy":"created"},
{"hard":"invented","easy":"created"},
{"hard":"inventing","easy":"creating"},
{"hard":"inventing","easy":"creating"},
{"hard":"inventor","easy":"creator"},
{"hard":"inventory","easy":"list"},
{"hard":"investigated","easy":"studied"},
{"hard":"invigorate","easy":"strengthen"},
{"hard":"irate","easy":"angry"},
{"hard":"irrelevant","easy":"not useful"},
{"hard":"irresolute","easy":"uncertain"},
{"hard":"irrespective","easy":"independant"},
{"hard":"irreverent","easy":"not serious"},
{"hard":"irrigate","easy":"water"},
{"hard":"irrigated","easy":"water"},
{"hard":"irrigating","easy":"watering"},
{"hard":"irrigation","easy":"watering"},
{"hard":"irritable","easy":"annoyed"},
{"hard":"isolate","easy":"separate"},
{"hard":"isolate","easy":"separate"},
{"hard":"isolated","easy":"separated"},
{"hard":"issued","easy":"gave"},
{"hard":"issued","easy":"gave"},
{"hard":"issuing","easy":"giving "},
{"hard":"issuing","easy":"giving"},
{"hard":"iterated","easy":"repeated"},
{"hard":"iteration","easy":"time"},
{"hard":"itinerary","easy":"plan"},
{"hard":"jabbed","easy":"poked"},
{"hard":"jackpot","easy":"prize"},
{"hard":"jaded","easy":"tired"},
{"hard":"jamboree","easy":"party"},
{"hard":"jargon","easy":"idiom"},
{"hard":"jaunt","easy":"trip"},
{"hard":"jaunty","easy":"happy"},
{"hard":"jeer","easy":"make fun of"},
{"hard":"jeering","easy":"making fun of"},
{"hard":"jeopardize","easy":"risk"},
{"hard":"jest","easy":"make fun of"},
{"hard":"jesting","easy":"making fun of"},
{"hard":"jiggle","easy":"shake"},
{"hard":"jiggled","easy":"shook"},
{"hard":"jiggling","easy":"shaking"},
{"hard":"jitter","easy":"shake"},
{"hard":"jittered","easy":"shook"},
{"hard":"jittering","easy":"shaking"},
{"hard":"jolly","easy":"happy"},
{"hard":"jot","easy":"write"},
{"hard":"joted","easy":"wrote"},
{"hard":"joting","easy":"writing"},
{"hard":"jotted","easy":"wrote"},
{"hard":"jotted","easy":"wrote"},
{"hard":"jovial","easy":"happy"},
{"hard":"joy","easy":"happiness"},
{"hard":"joyful","easy":"happy"},
{"hard":"joyful","easy":"happy"},
{"hard":"joyless","easy":"sad"},
{"hard":"joyous","easy":"happy"},
{"hard":"jubilant","easy":"happy"},
{"hard":"jubilation","easy":"happiness"},
{"hard":"jumbled","easy":"mixed"},
{"hard":"jumbling","easy":"mixing "},
{"hard":"jumbo","easy":"large"},
{"hard":"junction","easy":"cross"},
{"hard":"junk","easy":"garbage"},
{"hard":"juxtapose","easy":"compare"},
{"hard":"juxtapose","easy":"compare"},
{"hard":"juxtaposed","easy":"compared"},
{"hard":"juxtaposing","easy":"comparing"},
{"hard":"juxtaposition","easy":"comparison"},
{"hard":"kidding","easy":"joking"},
{"hard":"kidnap","easy":"take"},
{"hard":"kindly","easy":"nicely"},
{"hard":"knack","easy":"skill"},
{"hard":"knapsack","easy":"backpack"},
{"hard":"knickers","easy":"shorts"},
{"hard":"know-how","easy":"knowledge "},
{"hard":"knucklehead","easy":"idiot"},
{"hard":"kook","easy":"crazy person"},
{"hard":"kooky","easy":"crazy"},
{"hard":"labored","easy":"worked"},
{"hard":"laborer","easy":"worker"},
{"hard":"laborers","easy":"workers"},
{"hard":"laboring","easy":"working"},
{"hard":"laboured","easy":"worked"},
{"hard":"laboured","easy":"worked"},
{"hard":"labouring","easy":"working"},
{"hard":"laceration","easy":"wound"},
{"hard":"lacked","easy":"didn't have"},
{"hard":"lacked","easy":"missed"},
{"hard":"lacking","easy":"missing"},
{"hard":"lacking","easy":"missing"},
{"hard":"lackluster","easy":"boring"},
{"hard":"laden","easy":"filled"},
{"hard":"lager","easy":"beer"},
{"hard":"lagoon","easy":"lake"},
{"hard":"lame","easy":"uncool"},
{"hard":"lard","easy":"fat "},
{"hard":"large","easy":"big"},
{"hard":"large scale","easy":"big"},
{"hard":"largely","easy":"mostly "},
{"hard":"larger","easy":"bigger"},
{"hard":"largest","easy":"biggest"},
{"hard":"latch","easy":"lock"},
{"hard":"laudable","easy":"good"},
{"hard":"lavatory","easy":"bathroom"},
{"hard":"lavish","easy":"rich"},
{"hard":"leap","easy":"jump"},
{"hard":"leaped","easy":"jumped"},
{"hard":"leaping","easy":"jumping"},
{"hard":"leapt","easy":"jumped"},
{"hard":"learnt","easy":"learned"},
{"hard":"lecturer","easy":"teacher"},
{"hard":"legend","easy":"story"},
{"hard":"legible","easy":"clear "},
{"hard":"legislation","easy":"law"},
{"hard":"legitimate","easy":"real"},
{"hard":"lesion","easy":"wound"},
{"hard":"liability","easy":"danger"},
{"hard":"liable","easy":"responsible"},
{"hard":"liberate","easy":"free"},
{"hard":"liberated","easy":"freed"},
{"hard":"liberating","easy":"freeing"},
{"hard":"likelihood","easy":"chance"},
{"hard":"linkage","easy":"connection"},
{"hard":"linked","easy":"connected"},
{"hard":"linking","easy":"connecting"},
{"hard":"liquor","easy":"alcohol"},
{"hard":"listless","easy":"weak"},
{"hard":"listlessly","easy":"weakly"},
{"hard":"literally","easy":"actually"},
{"hard":"livelihood","easy":"money"},
{"hard":"livestock","easy":"animals "},
{"hard":"loathe","easy":"hate"},
{"hard":"locals","easy":"people"},
{"hard":"locate","easy":"find"},
{"hard":"locating","easy":"finding"},
{"hard":"locator","easy":"finder"},
{"hard":"logged","easy":"recorded"},
{"hard":"logging","easy":"recording"},
{"hard":"loner","easy":"loser"},
{"hard":"long winded","easy":"wordy"},
{"hard":"lovely","easy":"very nice"},
{"hard":"lugged","easy":"pulled"},
{"hard":"lugging","easy":"pulling"},
{"hard":"lukewarm","easy":"warm"},
{"hard":"lumped","easy":"put"},
{"hard":"lumping","easy":"putting"},
{"hard":"lunge","easy":"reach"},
{"hard":"lunged","easy":"reached"},
{"hard":"lunging","easy":"reaching"},
{"hard":"lush","easy":"rich"},
{"hard":"lust","easy":"desire"},
{"hard":"luxurious","easy":"nice"},
{"hard":"lynch","easy":"kill"},
{"hard":"lyrics","easy":"words"},
{"hard":"macro","easy":"large"},
{"hard":"madness","easy":"craziness"},
{"hard":"mailed","easy":"sent"},
{"hard":"mainly","easy":"mostly"},
{"hard":"maintain","easy":"keep"},
{"hard":"maintained","easy":"kept"},
{"hard":"maintaining","easy":"keeping"},
{"hard":"maintaining","easy":"keeping"},
{"hard":"majestic","easy":"beautiful"},
{"hard":"malady","easy":"injury"},
{"hard":"malefactor","easy":"wrongdoer"},
{"hard":"malfunction","easy":"error"},
{"hard":"malfunctioning","easy":"breaking"},
{"hard":"malice","easy":"hate"},
{"hard":"malignity","easy":"hate"},
{"hard":"mallet","easy":"hammer"},
{"hard":"mandatory","easy":"necessary"},
{"hard":"mane","easy":"hair"},
{"hard":"maneuver","easy":"move"},
{"hard":"maneuvered","easy":"moved"},
{"hard":"maneuvering","easy":"moving"},
{"hard":"mangle","easy":"damage"},
{"hard":"mangled","easy":"broken"},
{"hard":"mangling","easy":"damaging"},
{"hard":"manifestly","easy":"clearly"},
{"hard":"manifesto","easy":"statement "},
{"hard":"manner","easy":"act"},
{"hard":"mannerly","easy":"respectful"},
{"hard":"mansion","easy":"large house"},
{"hard":"manufacture","easy":"make"},
{"hard":"manufactured","easy":"made"},
{"hard":"manufactured","easy":"made"},
{"hard":"manufacturers","easy":"makers"},
{"hard":"manuscript","easy":"book"},
{"hard":"marched","easy":"walked"},
{"hard":"massive","easy":"large"},
{"hard":"massively","easy":"largely"},
{"hard":"materialize","easy":"happen"},
{"hard":"materialized","easy":"happened"},
{"hard":"materializing","easy":"happening"},
{"hard":"maternal","easy":"motherly"},
{"hard":"maternity","easy":"pregnancy"},
{"hard":"mathematics","easy":"math"},
{"hard":"meadow","easy":"field"},
{"hard":"medley","easy":"mix"},
{"hard":"melancholic","easy":"sad"},
{"hard":"melancholy","easy":"sadness"},
{"hard":"mellow","easy":"soft"},
{"hard":"memo","easy":"note"},
{"hard":"menace","easy":"danger"},
{"hard":"mentality","easy":"thinking"},
{"hard":"mention","easy":"talk about"},
{"hard":"mentioned","easy":"talked about"},
{"hard":"mentioning","easy":"talking about"},
{"hard":"merchandise","easy":"products"},
{"hard":"merely","easy":"only"},
{"hard":"merely","easy":"only"},
{"hard":"merry","easy":"happy"},
{"hard":"method","easy":"way"},
{"hard":"methodical","easy":"careful"},
{"hard":"metropolis","easy":"city"},
{"hard":"microscopic","easy":"very small"},
{"hard":"mid","easy":"middle"},
{"hard":"midway","easy":"half way"},
{"hard":"migraine","easy":"headache"},
{"hard":"migrate","easy":"move"},
{"hard":"migrate","easy":"move"},
{"hard":"migrate","easy":"move"},
{"hard":"migrated","easy":"moved"},
{"hard":"migrated","easy":"moved"},
{"hard":"migrating","easy":"moving"},
{"hard":"migrating","easy":"moving"},
{"hard":"mingled","easy":"mixed"},
{"hard":"miniature","easy":"many"},
{"hard":"miraculous","easy":"amazing"},
{"hard":"miraculous","easy":"amazing"},
{"hard":"misapprehension","easy":"confusion"},
{"hard":"miscellany","easy":"things"},
{"hard":"misconception","easy":"confusion"},
{"hard":"misconception","easy":"misunderstanding"},
{"hard":"misconduct","easy":"crime"},
{"hard":"misconstrued","easy":"misunderstood"},
{"hard":"misdeed","easy":"crime"},
{"hard":"misdemeanor","easy":"crime"},
{"hard":"misdemeanour","easy":"crime"},
{"hard":"miserable","easy":"very sad"},
{"hard":"misery","easy":"sadness"},
{"hard":"misfortunate","easy":"unlucky"},
{"hard":"misfortune","easy":"bad luck"},
{"hard":"mishap","easy":"mistake"},
{"hard":"misinterpret","easy":"misunderstand"},
{"hard":"misinterpreted","easy":"misunderstood"},
{"hard":"misinterpreting","easy":"misunderstanding"},
{"hard":"mistaken","easy":"wrong"},
{"hard":"mistaken","easy":"wrong"},
{"hard":"mistakenly","easy":"wrongly"},
{"hard":"mistook","easy":"confused"},
{"hard":"mixture","easy":"mix"},
{"hard":"mobilize","easy":"prepare"},
{"hard":"mobilized","easy":"prepared"},
{"hard":"mobilizing","easy":"preparing"},
{"hard":"mock","easy":"make fun of"},
{"hard":"mocked","easy":"made fun of"},
{"hard":"mocking","easy":"making fun of"},
{"hard":"modification","easy":"change"},
{"hard":"modified","easy":"changed"},
{"hard":"modifying","easy":"changing"},
{"hard":"moist","easy":"wet"},
{"hard":"moisture","easy":"wetness"},
{"hard":"momentarily","easy":"quickly"},
{"hard":"momentous","easy":"important"},
{"hard":"momentous","easy":"important"},
{"hard":"morsel","easy":"bit"},
{"hard":"motivate","easy":"excite"},
{"hard":"motivated","easy":"excited"},
{"hard":"motive","easy":"reason"},
{"hard":"motorway","easy":"highway"},
{"hard":"motto","easy":"saying"},
{"hard":"munchies","easy":"snacks"},
{"hard":"municipal","easy":"city"},
{"hard":"municipalities","easy":"towns"},
{"hard":"municipality","easy":"town"},
{"hard":"murdered","easy":"killed"},
{"hard":"murdered","easy":"killed"},
{"hard":"murderer","easy":"killer"},
{"hard":"murdering","easy":"killing"},
{"hard":"murdering","easy":"killing"},
{"hard":"murky","easy":"dark"},
{"hard":"muster","easy":"get"},
{"hard":"mustering","easy":"getting "},
{"hard":"mute","easy":"silent"},
{"hard":"mute","easy":"silent"},
{"hard":"muted","easy":"silenced"},
{"hard":"muted","easy":"silenced"},
{"hard":"mutilate","easy":"destroy"},
{"hard":"mutilated","easy":"destroyed"},
{"hard":"mutilating","easy":"destroying"},
{"hard":"muting","easy":"silencing"},
{"hard":"mutter","easy":"say"},
{"hard":"muttered","easy":"said"},
{"hard":"muttering","easy":"saying"},
{"hard":"mystified","easy":"amazed"},
{"hard":"mystify","easy":"amaze"},
{"hard":"mystifying","easy":"amazing"},
{"hard":"nab","easy":"take"},
{"hard":"nagged","easy":"complained"},
{"hard":"nagging","easy":"complaining"},
{"hard":"nah","easy":"no"},
{"hard":"namesake","easy":"name"},
{"hard":"narrative","easy":"story"},
{"hard":"narratives","easy":"stories"},
{"hard":"narrowly","easy":"barely"},
{"hard":"naught","easy":"nothing"},
{"hard":"nay","easy":"no"},
{"hard":"necessitate","easy":"need"},
{"hard":"necessitated","easy":"needed"},
{"hard":"necessitating","easy":"needing"},
{"hard":"nefarious","easy":"very bad"},
{"hard":"nefariously","easy":"very wrongly"},
{"hard":"neglect","easy":"ignore"},
{"hard":"neglectful","easy":"careless"},
{"hard":"neglectfully","easy":"carelessly"},
{"hard":"negligible","easy":"unimportant"},
{"hard":"negligible","easy":"unimportant"},
{"hard":"negotiate","easy":"argue"},
{"hard":"negotiation","easy":"argument"},
{"hard":"newcomer","easy":"new person"},
{"hard":"newcomers","easy":"new people"},
{"hard":"newfangled","easy":"different"},
{"hard":"nibble","easy":"bite"},
{"hard":"nibbled","easy":"bit"},
{"hard":"nibbling","easy":"biting"},
{"hard":"niche","easy":"place"},
{"hard":"nigh","easy":"near"},
{"hard":"nil","easy":"nothing"},
{"hard":"nimble","easy":"quick"},
{"hard":"ninetieth","easy":"90th"},
{"hard":"nip","easy":"bite"},
{"hard":"nipped","easy":"bit"},
{"hard":"nipping","easy":"biting"},
{"hard":"nominate","easy":"suggest"},
{"hard":"nominated","easy":"suggested"},
{"hard":"nominating","easy":"suggesting"},
{"hard":"non-compliant","easy":"disagreeable"},
{"hard":"nondescript","easy":"normal"},
{"hard":"nope","easy":"no"},
{"hard":"nosy","easy":"rude"},
{"hard":"notable","easy":"important"},
{"hard":"notably","easy":"importantly"},
{"hard":"noteworthy","easy":"important"},
{"hard":"notified","easy":"tell"},
{"hard":"notified","easy":"told"},
{"hard":"notified","easy":"told"},
{"hard":"notifies","easy":"tells"},
{"hard":"notify","easy":"tell"},
{"hard":"notifying","easy":"telling"},
{"hard":"notifying","easy":"telling"},
{"hard":"notion","easy":"idea"},
{"hard":"novels","easy":"stories"},
{"hard":"nowadays","easy":"today"},
{"hard":"numerous","easy":"many"},
{"hard":"obfuscated","easy":"confusing"},
{"hard":"objected","easy":"disagreed "},
{"hard":"objecting","easy":"disagreeing"},
{"hard":"objectives","easy":"goals"},
{"hard":"obtain","easy":"get"},
{"hard":"obtained","easy":"got"},
{"hard":"obvious","easy":"clear"},
{"hard":"obviously","easy":"clearly"},
{"hard":"occasion","easy":"time"},
{"hard":"odor","easy":"smell"},
{"hard":"ominous","easy":"scary"},
{"hard":"onset","easy":"starting"},
{"hard":"ophthalmologist","easy":"eye-expert"},
{"hard":"opportunity","easy":"chance"},
{"hard":"optimal","easy":"best"},
{"hard":"optimal","easy":"best"},
{"hard":"optimize","easy":"improve"},
{"hard":"optimum","easy":"best"},
{"hard":"opulent","easy":"rich"},
{"hard":"ordinarily","easy":"normally"},
{"hard":"ordinarily","easy":"normally"},
{"hard":"ordinary","easy":"normal"},
{"hard":"orifice","easy":"hole"},
{"hard":"originally","easy":"first"},
{"hard":"oust","easy":"remove"},
{"hard":"ousted","easy":"removed"},
{"hard":"ousting","easy":"removing"},
{"hard":"outdo","easy":"beat"},
{"hard":"outrage","easy":"anger"},
{"hard":"outraged","easy":"angry"},
{"hard":"outskirts","easy":"edge"},
{"hard":"outweigh","easy":"weigh more than"},
{"hard":"overdue","easy":"late"},
{"hard":"overjoyed","easy":"very happy"},
{"hard":"oversight","easy":"mistake"},
{"hard":"pact","easy":"agreement"},
{"hard":"pandemonium","easy":"craziness"},
{"hard":"paraphernalia","easy":"things"},
{"hard":"parodied","easy":"made fun of"},
{"hard":"parody","easy":"make fun of"},
{"hard":"partook","easy":"took part"},
{"hard":"paternal","easy":"fatherly"},
{"hard":"paternalistic","easy":"fatherly"},
{"hard":"paw","easy":"foot"},
{"hard":"paws","easy":"feet"},
{"hard":"peered","easy":"looked"},
{"hard":"peering","easy":"looking"},
{"hard":"pejorative","easy":"mean"},
{"hard":"pending","easy":"waiting"},
{"hard":"pensive","easy":"thoughtful"},
{"hard":"perceive","easy":"see"},
{"hard":"performance","easy":"show"},
{"hard":"perhaps","easy":"maybe"},
{"hard":"peril","easy":"great danger"},
{"hard":"perilous","easy":"dangerous"},
{"hard":"perils","easy":"dangers"},
{"hard":"periodically","easy":"sometimes"},
{"hard":"permitted","easy":"let"},
{"hard":"permitting","easy":"letting"},
{"hard":"persist","easy":"continue"},
{"hard":"persisted","easy":"continued"},
{"hard":"persisting","easy":"continuing"},
{"hard":"perspective","easy":"view"},
{"hard":"pertains","easy":"matters"},
{"hard":"pertinent","easy":"important"},
{"hard":"peruse","easy":"look at"},
{"hard":"perused","easy":"looked at"},
{"hard":"perusing","easy":"looking at"},
{"hard":"phenomenal","easy":"great "},
{"hard":"phenomenally","easy":"very"},
{"hard":"photo","easy":"picture"},
{"hard":"photos","easy":"pictures"},
{"hard":"physician","easy":"doctor"},
{"hard":"pic","easy":"picture"},
{"hard":"pieced","easy":"put"},
{"hard":"piecing","easy":"putting"},
{"hard":"pistol","easy":"gun"},
{"hard":"pivotal","easy":"important"},
{"hard":"placed","easy":"put"},
{"hard":"placed","easy":"put"},
{"hard":"placid","easy":"quiet"},
{"hard":"placidly","easy":"quietly"},
{"hard":"plagued","easy":"troubled"},
{"hard":"plausible","easy":"possible"},
{"hard":"plead","easy":"beg"},
{"hard":"pleaded","easy":"begged"},
{"hard":"pleasant","easy":"nice"},
{"hard":"pleasant","easy":"good"},
{"hard":"pleased","easy":"happy"},
{"hard":"pleasing","easy":"good"},
{"hard":"pleasing","easy":"nice"},
{"hard":"pleasurable","easy":"good"},
{"hard":"pleasurable","easy":"nice"},
{"hard":"plentiful","easy":"full"},
{"hard":"plenty","easy":"lots"},
{"hard":"ploy","easy":"trick"},
{"hard":"plucked","easy":"took "},
{"hard":"plugging","easy":"putting"},
{"hard":"plump","easy":"round"},
{"hard":"plunge","easy":"fall"},
{"hard":"plunged","easy":"fell"},
{"hard":"plunging","easy":"falling"},
{"hard":"plush","easy":"rich"},
{"hard":"ply","easy":"layer"},
{"hard":"polished","easy":"cleaned"},
{"hard":"polishing","easy":"cleaning"},
{"hard":"pompous","easy":"rude"},
{"hard":"pompous","easy":"self-important"},
{"hard":"pompously","easy":"self-importantly"},
{"hard":"ponder","easy":"thought"},
{"hard":"ponder","easy":"give thought to"},
{"hard":"pondered","easy":"gave thought to"},
{"hard":"pondering","easy":"thinking about"},
{"hard":"pondering","easy":"giving thought to"},
{"hard":"ponders","easy":"gives thought to"},
{"hard":"pony","easy":"small horse"},
{"hard":"pooch","easy":"dog"},
{"hard":"populace","easy":"public"},
{"hard":"portly","easy":"fat"},
{"hard":"possess","easy":"have"},
{"hard":"possessing","easy":"having"},
{"hard":"postponed","easy":"delayed"},
{"hard":"postponed","easy":"delay"},
{"hard":"postponing","easy":"delaying"},
{"hard":"posture","easy":"body position"},
{"hard":"potent","easy":"strong"},
{"hard":"potentially","easy":"maybe"},
{"hard":"potentially","easy":"maybe"},
{"hard":"pouch","easy":"bag"},
{"hard":"pouches","easy":"bags"},
{"hard":"poultry","easy":"chicken"},
{"hard":"powerful","easy":"strong"},
{"hard":"praising","easy":"thanking"},
{"hard":"preceded","easy":"came before"},
{"hard":"precise","easy":"tight"},
{"hard":"predict","easy":"guess"},
{"hard":"predicted","easy":"guessed"},
{"hard":"predicted","easy":"guessed"},
{"hard":"predicting","easy":"guessing"},
{"hard":"prediction","easy":"guess"},
{"hard":"prediction","easy":"des"},
{"hard":"predominately","easy":"mostly"},
{"hard":"prefer","easy":"hope"},
{"hard":"preferably","easy":"hopefully"},
{"hard":"preference","easy":"choice"},
{"hard":"preferences","easy":"desires"},
{"hard":"preluded","easy":"came before"},
{"hard":"preluding","easy":"coming before"},
{"hard":"premature","easy":"early"},
{"hard":"prematurely","easy":"early"},
{"hard":"prepare","easy":"get ready"},
{"hard":"prepared","easy":"ready"},
{"hard":"prepared","easy":"ready"},
{"hard":"preparing","easy":"getting ready"},
{"hard":"preparing","easy":"getting  ready"},
{"hard":"preserve","easy":"keep"},
{"hard":"preserved","easy":"kept"},
{"hard":"preserving","easy":"keeping"},
{"hard":"presumably","easy":"probably"},
{"hard":"presume","easy":"assume"},
{"hard":"presuming","easy":"assuming"},
{"hard":"presuppose","easy":"assume"},
{"hard":"presuppose","easy":"assume"},
{"hard":"presupposed","easy":"assumed"},
{"hard":"presupposing","easy":"assuming"},
{"hard":"presupposition","easy":"assumption"},
{"hard":"previous","easy":"earlier"},
{"hard":"previously","easy":"earlier"},
{"hard":"previously","easy":"earlier"},
{"hard":"primarily","easy":"mostly"},
{"hard":"primary","easy":"first"},
{"hard":"principle","easy":"idea"},
{"hard":"proceed","easy":"go ahead"},
{"hard":"proceed","easy":"went"},
{"hard":"proclaim","easy":"say"},
{"hard":"procure","easy":"get"},
{"hard":"procured","easy":"got"},
{"hard":"procures","easy":"gets"},
{"hard":"procuring","easy":"getting"},
{"hard":"produced","easy":"made"},
{"hard":"producing","easy":"making"},
{"hard":"producing","easy":"making"},
{"hard":"product","easy":"thing"},
{"hard":"products","easy":"things"},
{"hard":"profess","easy":"claim"},
{"hard":"professed","easy":"claimed"},
{"hard":"professing","easy":"claiming"},
{"hard":"professor","easy":"teacher"},
{"hard":"profoundly","easy":"very"},
{"hard":"project","easy":"gas"},
{"hard":"proliferation","easy":"spreading"},
{"hard":"prolific","easy":"everywhere"},
{"hard":"prominent","easy":"major"},
{"hard":"promptly","easy":"quickly"},
{"hard":"promptly","easy":"quickly"},
{"hard":"propel","easy":"push"},
{"hard":"propelled","easy":"pushed"},
{"hard":"propelling","easy":"pushing"},
{"hard":"proper","easy":"respectful"},
{"hard":"proper","easy":"right"},
{"hard":"proposition","easy":"choice"},
{"hard":"proprietor","easy":"owner"},
{"hard":"proprietors","easy":"owners"},
{"hard":"prosaic","easy":"common"},
{"hard":"prosper","easy":"do well"},
{"hard":"prospering","easy":"doing well"},
{"hard":"prosperous","easy":"rich"},
{"hard":"protocol","easy":"rules"},
{"hard":"psalm","easy":"song"},
{"hard":"psyched","easy":"excited"},
{"hard":"pun","easy":"joke"},
{"hard":"punch","easy":"hit"},
{"hard":"punching","easy":"hitting"},
{"hard":"puncture","easy":"get in"},
{"hard":"punctured","easy":"entered"},
{"hard":"puncturing","easy":"getting in"},
{"hard":"purchased","easy":"bought"},
{"hard":"purchasing","easy":"buying"},
{"hard":"purifies","easy":"cleans"},
{"hard":"purify","easy":"clean"},
{"hard":"purifying","easy":"cleaning"},
{"hard":"purport","easy":"claim"},
{"hard":"purported","easy":"claimed"},
{"hard":"purporting","easy":"claiming"},
{"hard":"purposes","easy":"reasons"},
{"hard":"pursue","easy":"go after"},
{"hard":"pursued","easy":"went after"},
{"hard":"pursues","easy":"goes after"},
{"hard":"pursuing","easy":"going after"},
{"hard":"putrid","easy":"gross"},
{"hard":"quaint","easy":"nice"},
{"hard":"quaintly","easy":"nicely"},
{"hard":"quantities","easy":"amounts"},
{"hard":"quantity","easy":"number"},
{"hard":"quantity","easy":"amount"},
{"hard":"quarrel","easy":"fight"},
{"hard":"quarreling","easy":"fighting"},
{"hard":"quarrelled","easy":"font"},
{"hard":"quarrelled","easy":"font"},
{"hard":"quarrelling","easy":"fighting"},
{"hard":"queries","easy":"questions"},
{"hard":"query","easy":"question"},
{"hard":"querying","easy":"questing"},
{"hard":"queue","easy":"line"},
{"hard":"quirky","easy":"weird"},
{"hard":"quite","easy":"truly"},
{"hard":"radiated","easy":"spread"},
{"hard":"radiating","easy":"spreading"},
{"hard":"radically","easy":"greatly"},
{"hard":"raffle","easy":"ticket-competition"},
{"hard":"raging","easy":"angry"},
{"hard":"rage","easy":"anger"},
{"hard":"rapidly","easy":"quickly"},
{"hard":"ravel","easy":"twist"},
{"hard":"raveled","easy":"twisted"},
{"hard":"raveling","easy":"twisting"},
{"hard":"raze","easy":"burn"},
{"hard":"razed","easy":"burned"},
{"hard":"razing","easy":"burning"},
{"hard":"readily","easy":"quickly"},
{"hard":"realistic","easy":"real"},
{"hard":"realistically","easy":"really"},
{"hard":"reap","easy":"enjoy"},
{"hard":"reaped","easy":"enjoyed"},
{"hard":"reasoned","easy":"thought"},
{"hard":"reasoning","easy":"thinking"},
{"hard":"rebels","easy":"turn"},
{"hard":"recapitulates","easy":"repeat"},
{"hard":"recapitulation","easy":"repetition"},
{"hard":"receive","easy":"get"},
{"hard":"received","easy":"got"},
{"hard":"receives","easy":"gets"},
{"hard":"receiving","easy":"getting"},
{"hard":"recent","easy":"new"},
{"hard":"reclined","easy":"rested"},
{"hard":"reclining","easy":"rest"},
{"hard":"reclining","easy":"resting"},
{"hard":"recognize","easy":"remember"},
{"hard":"recognized","easy":"remembered"},
{"hard":"recollect","easy":"remember"},
{"hard":"recollection","easy":"memory"},
{"hard":"reek","easy":"smell"},
{"hard":"reeked","easy":"smelt"},
{"hard":"reeking","easy":"smelling"},
{"hard":"refine","easy":"improve"},
{"hard":"reform","easy":"change "},
{"hard":"reformed","easy":"changed"},
{"hard":"reforming","easy":"changing"},
{"hard":"regain","easy":"get back"},
{"hard":"regained","easy":"got back"},
{"hard":"regaining","easy":"getting back"},
{"hard":"regiment","easy":"plan"},
{"hard":"region","easy":"area"},
{"hard":"regulation","easy":"rule"},
{"hard":"rehabilitate","easy":"recover"},
{"hard":"rehabilitation","easy":"recovery"},
{"hard":"rehearsal","easy":"practice"},
{"hard":"rehearse","easy":"practice"},
{"hard":"rehearsed","easy":"practiced"},
{"hard":"rehearsing","easy":"practicing"},
{"hard":"reigned","easy":"ruled"},
{"hard":"reigning","easy":"ruling"},
{"hard":"reignite","easy":"restart"},
{"hard":"reignited","easy":"restarted"},
{"hard":"reigniting","easy":"restarting"},
{"hard":"reimburse","easy":"paid back"},
{"hard":"reimbursed","easy":"paid back"},
{"hard":"reimbursing","easy":"paying back"},
{"hard":"reinforcement","easy":"support"},
{"hard":"reinforcing","easy":"supporting"},
{"hard":"reinstate","easy":"put back"},
{"hard":"reinstated","easy":"put back"},
{"hard":"reinstates","easy":"puts back"},
{"hard":"reinstating","easy":"putting back"},
{"hard":"reiterate","easy":"repeat"},
{"hard":"reiterated","easy":"repeated"},
{"hard":"reiterating","easy":"repeating"},
{"hard":"reiteration","easy":"repetition"},
{"hard":"rejoice","easy":"celebrate"},
{"hard":"rejoicing","easy":"celebrating"},
{"hard":"relaxed","easy":"comfortable"},
{"hard":"relocate","easy":"move"},
{"hard":"relocated","easy":"moved "},
{"hard":"remark","easy":"statement"},
{"hard":"remarkable","easy":"amazing"},
{"hard":"remarking","easy":"saying"},
{"hard":"remorse","easy":"regret"},
{"hard":"remorseful","easy":"regretful"},
{"hard":"remorsefully","easy":"regretfully"},
{"hard":"removed","easy":"took away"},
{"hard":"removes","easy":"takes away"},
{"hard":"removing","easy":"taking away"},
{"hard":"rendition","easy":"version"},
{"hard":"renounce","easy":"give up"},
{"hard":"renouncing","easy":"giving up"},
{"hard":"renovate","easy":"change"},
{"hard":"renovated","easy":"changed"},
{"hard":"renovating","easy":"changing"},
{"hard":"repair","easy":"fix"},
{"hard":"repaired","easy":"fixed"},
{"hard":"repaired","easy":"fixed"},
{"hard":"repairing","easy":"fixing"},
{"hard":"repairing","easy":"fixing"},
{"hard":"replenish","easy":"refill"},
{"hard":"replenished","easy":"refilled"},
{"hard":"replenishing","easy":"refilling"},
{"hard":"replied","easy":"answered"},
{"hard":"replied","easy":"answered"},
{"hard":"reply","easy":"answer"},
{"hard":"reporter","easy":"writer"},
{"hard":"reprehensible","easy":"terrible"},
{"hard":"reprimand","easy":"criticize"},
{"hard":"repugnant","easy":"terrible"},
{"hard":"repulsive","easy":"terrible"},
{"hard":"requested","easy":"asked for"},
{"hard":"requesting","easy":"asking for"},
{"hard":"require","easy":"need"},
{"hard":"required","easy":"needed"},
{"hard":"requiring","easy":"needing"},
{"hard":"requisite","easy":"necessary"},
{"hard":"rescue","easy":"save"},
{"hard":"rescue","easy":"save"},
{"hard":"rescued","easy":"saved"},
{"hard":"rescued","easy":"saved"},
{"hard":"rescuer","easy":"saver"},
{"hard":"rescuing","easy":"saving"},
{"hard":"rescuing","easy":"saving"},
{"hard":"researched","easy":"studied"},
{"hard":"researching","easy":"studying"},
{"hard":"resemblance","easy":"similarity"},
{"hard":"resemble","easy":"look like"},
{"hard":"resembled","easy":"looked like"},
{"hard":"resembled","easy":"was like"},
{"hard":"resembles","easy":"looks like"},
{"hard":"resembles","easy":"is like"},
{"hard":"resembling","easy":"looking like"},
{"hard":"reset","easy":"restart"},
{"hard":"resetting","easy":"restarting"},
{"hard":"reside","easy":"live"},
{"hard":"reside","easy":"live"},
{"hard":"resided","easy":"lived"},
{"hard":"resided","easy":"lived"},
{"hard":"residing","easy":"living"},
{"hard":"residing","easy":"living"},
{"hard":"resign","easy":"leave"},
{"hard":"resigned","easy":"left"},
{"hard":"resilient","easy":"strong"},
{"hard":"respond","easy":"answer"},
{"hard":"responded","easy":"answered"},
{"hard":"retain","easy":"keep"},
{"hard":"retain","easy":"keep"},
{"hard":"retained","easy":"kept"},
{"hard":"retort","easy":"answer"},
{"hard":"retreating","easy":"getting"},
{"hard":"retrieve","easy":"get "},
{"hard":"retrieve","easy":"get"},
{"hard":"retrieved","easy":"got"},
{"hard":"retrieved","easy":"got"},
{"hard":"retrieving","easy":"getting"},
{"hard":"reveal","easy":"show"},
{"hard":"revealed","easy":"showed"},
{"hard":"revere","easy":"respect"},
{"hard":"revered","easy":"respected"},
{"hard":"reverence","easy":"respect"},
{"hard":"revise","easy":"change"},
{"hard":"revised","easy":"changed"},
{"hard":"revising","easy":"changing"},
{"hard":"revision","easy":"change"},
{"hard":"revolting","easy":"terrible"},
{"hard":"revolving","easy":"turning"},
{"hard":"ridicule","easy":"make fun of"},
{"hard":"ridiculed","easy":"made fun of"},
{"hard":"ridiculing","easy":"making fun of"},
{"hard":"rife","easy":"rich"},
{"hard":"rifle","easy":"gun"},
{"hard":"rigid","easy":"hard"},
{"hard":"ripple","easy":"small wave"},
{"hard":"rival","easy":"enemy"},
{"hard":"rivalled","easy":"competed with"},
{"hard":"robust","easy":"strong"},
{"hard":"robustly","easy":"strongly"},
{"hard":"rotate","easy":"turn"},
{"hard":"rouse","easy":"excite"},
{"hard":"route","easy":"path"},
{"hard":"rsvp","easy":"respond"},
{"hard":"rudimentary","easy":"basic"},
{"hard":"rumor","easy":"story"},
{"hard":"rumors","easy":"stories"},
{"hard":"rumour","easy":"story"},
{"hard":"rumours","easy":"stories"},
{"hard":"rupture","easy":"break"},
{"hard":"ruptured","easy":"broke"},
{"hard":"rupturing","easy":"breaking"},
{"hard":"sacred","easy":"important"},
{"hard":"salivate","easy":"drool"},
{"hard":"salivated","easy":"drooled"},
{"hard":"salivating","easy":"drooling"},
{"hard":"sanctified","easy":"important"},
{"hard":"satisfying","easy":"good"},
{"hard":"satisfying","easy":"nice"},
{"hard":"scheme","easy":"plan"},
{"hard":"scorch","easy":"burn"},
{"hard":"scorches","easy":"burns"},
{"hard":"scour","easy":"search"},
{"hard":"scoured","easy":"searched"},
{"hard":"scrolled","easy":"rolled"},
{"hard":"scrolling","easy":"rolling"},
{"hard":"scrutinize","easy":"criticize"},
{"hard":"scrutinized","easy":"criticized"},
{"hard":"scrutinizing","easy":"criticizing"},
{"hard":"scurried","easy":"ran"},
{"hard":"scurry","easy":"run"},
{"hard":"scurrying","easy":"running"},
{"hard":"section","easy":"part"},
{"hard":"seek","easy":"search for"},
{"hard":"segment","easy":"part"},
{"hard":"segment","easy":"part"},
{"hard":"segregate","easy":"separate"},
{"hard":"segregated","easy":"separated"},
{"hard":"segregating","easy":"separating"},
{"hard":"seldom","easy":"rarely"},
{"hard":"select","easy":"choose"},
{"hard":"selected","easy":"chose"},
{"hard":"selecting","easy":"choosing"},
{"hard":"selection","easy":"choice"},
{"hard":"seminar","easy":"class"},
{"hard":"sensation","easy":"feeling"},
{"hard":"sever","easy":"cut"},
{"hard":"several","easy":"some"},
{"hard":"severe","easy":"serious"},
{"hard":"severed","easy":"cut"},
{"hard":"severely","easy":"seriously"},
{"hard":"severing","easy":"cutting"},
{"hard":"shall","easy":"will"},
{"hard":"shall","easy":"will"},
{"hard":"shameful","easy":"bad"},
{"hard":"shatter","easy":"break"},
{"hard":"shattered","easy":"broke"},
{"hard":"shattering","easy":"breaking"},
{"hard":"shifted","easy":"moved"},
{"hard":"shifting","easy":"moved"},
{"hard":"shifting","easy":"moving"},
{"hard":"shifting","easy":"moving"},
{"hard":"shimmered","easy":"danced "},
{"hard":"shimmering","easy":"dancing "},
{"hard":"shiny","easy":"bright"},
{"hard":"shoddy","easy":"poor"},
{"hard":"shouldâve","easy":"should have"},
{"hard":"shouldn't","easy":"should not "},
{"hard":"shout","easy":"yell"},
{"hard":"shouted","easy":"yelled"},
{"hard":"shouting","easy":"yelling"},
{"hard":"shove","easy":"push"},
{"hard":"shoved","easy":"pushed"},
{"hard":"shoving","easy":"pushing"},
{"hard":"shredded","easy":"ripped"},
{"hard":"shredding","easy":"ripping"},
{"hard":"shrivel","easy":"shrink"},
{"hard":"shrivelling","easy":"shrinking"},
{"hard":"shrivelled","easy":"shrunk"},
{"hard":"shutting","easy":"closing"},
{"hard":"silent","easy":"quiet"},
{"hard":"sillier","easy":"funnier"},
{"hard":"silliest","easy":"funniest"},
{"hard":"silly","easy":"funny"},
{"hard":"similarly","easy":"also"},
{"hard":"simmer","easy":"boil"},
{"hard":"simmered","easy":"boiled "},
{"hard":"simmering","easy":"boiling"},
{"hard":"simultaneously","easy":"at the same time"},
{"hard":"sinful","easy":"bad"},
{"hard":"singe","easy":"burn"},
{"hard":"situate","easy":"place"},
{"hard":"situated","easy":"placed"},
{"hard":"situating","easy":"placing"},
{"hard":"sixtieth","easy":"60th"},
{"hard":"sizable","easy":"big"},
{"hard":"skidded","easy":"slipped"},
{"hard":"skidding","easy":"slipping"},
{"hard":"skill","easy":"ability"},
{"hard":"skilled","easy":"good"},
{"hard":"skillful"},
{"hard":"skinny","easy":"thin"},
{"hard":"slain","easy":"killed"},
{"hard":"slam","easy":"hit"},
{"hard":"slaughtered","easy":"killed"},
{"hard":"slaughtering","easy":"killing"},
{"hard":"slay","easy":"kill"},
{"hard":"slayer","easy":"killer"},
{"hard":"slaying","easy":"killing"},
{"hard":"sliced","easy":"cut"},
{"hard":"slicing","easy":"cutting"},
{"hard":"slid","easy":"slipped"},
{"hard":"slides","easy":"slips"},
{"hard":"sliding","easy":"slipping"},
{"hard":"slight","easy":"small"},
{"hard":"slighted","easy":"hurt"},
{"hard":"slightest","easy":"smallest"},
{"hard":"slipped","easy":"fell"},
{"hard":"slipping","easy":"falling"},
{"hard":"slumber","easy":"sleep"},
{"hard":"slumbered","easy":"slept"},
{"hard":"slumbering","easy":"sleeping"},
{"hard":"slumbers","easy":"sleeps"},
{"hard":"smacked","easy":"hit"},
{"hard":"smacking","easy":"hitting"},
{"hard":"smash","easy":"hit"},
{"hard":"smirk","easy":"smile"},
{"hard":"smirked","easy":"smiled"},
{"hard":"smuggle","easy":"sneak"},
{"hard":"smuggled","easy":"snook"},
{"hard":"smuggling","easy":"sneaking"},
{"hard":"snicker","easy":"laugh"},
{"hard":"snickered","easy":"laughed"},
{"hard":"snickering","easy":"laughing"},
{"hard":"snip","easy":"cut"},
{"hard":"snooze","easy":"sleep"},
{"hard":"snoozed","easy":"slept"},
{"hard":"snoozing","easy":"sleeping"},
{"hard":"snout","easy":"nose"},
{"hard":"snug","easy":"comfortable"},
{"hard":"snug","easy":"tight"},
{"hard":"soar","easy":"fly"},
{"hard":"soared","easy":"flew"},
{"hard":"soaring","easy":"flying"},
{"hard":"sobbed","easy":"cried"},
{"hard":"sobbing","easy":"crying"},
{"hard":"sofa","easy":"couch"},
{"hard":"solemn","easy":"serious"},
{"hard":"solicitous","easy":"respectful"},
{"hard":"somber","easy":"serious"},
{"hard":"sore","easy":"painful"},
{"hard":"sorority","easy":"club"},
{"hard":"sorrow","easy":"sadness"},
{"hard":"spawned","easy":"created"},
{"hard":"speak","easy":"talk"},
{"hard":"speaker","easy":"talker"},
{"hard":"speaking","easy":"talking"},
{"hard":"specialist","easy":"expert"},
{"hard":"specifies","easy":"decides"},
{"hard":"specifying","easy":"deciding"},
{"hard":"specimen","easy":"example"},
{"hard":"spectacular","easy":"amazing"},
{"hard":"spectacularly","easy":"amazingly"},
{"hard":"spectacularly","easy":"very"},
{"hard":"speculate","easy":"guess"},
{"hard":"speculated","easy":"guessed"},
{"hard":"spinning","easy":"turning"},
{"hard":"spiraled","easy":"twisted"},
{"hard":"spiraling","easy":"twisting"},
{"hard":"spiralled","easy":"twisted"},
{"hard":"spiralling","easy":"twisting"},
{"hard":"spoke","easy":"talked"},
{"hard":"spoken","easy":"said"},
{"hard":"sprain","easy":"twist"},
{"hard":"sprained","easy":"twisted"},
{"hard":"spraining","easy":"twisting"},
{"hard":"spun","easy":"turned"},
{"hard":"squad","easy":"team"},
{"hard":"stale","easy":"old"},
{"hard":"stated","easy":"said"},
{"hard":"stating","easy":"saying"},
{"hard":"stimulate","easy":"excite"},
{"hard":"stimulated","easy":"excited"},
{"hard":"stipulate","easy":"saying"},
{"hard":"stipulated","easy":"said"},
{"hard":"stipulates","easy":"says"},
{"hard":"stipulating","easy":"saying"},
{"hard":"stored","easy":"kept"},
{"hard":"storing","easy":"keeping"},
{"hard":"strenuous","easy":"hard"},
{"hard":"struggle","easy":"fight"},
{"hard":"struggled","easy":"fought"},
{"hard":"struggling","easy":"fighting"},
{"hard":"subsequent","easy":"following "},
{"hard":"subsequently","easy":"consequently"},
{"hard":"subsequently","easy":"after "},
{"hard":"subset","easy":"part"},
{"hard":"substantiate","easy":"support"},
{"hard":"substituting","easy":"switching"},
{"hard":"subterranean","easy":"underground"},
{"hard":"suitable","easy":"ok"},
{"hard":"suitable","easy":"ok"},
{"hard":"superficial","easy":"cheap"},
{"hard":"superficially","easy":"lightly"},
{"hard":"superfluous","easy":"unnecessary"},
{"hard":"superfluous","easy":"unnecessary"},
{"hard":"superfluously","easy":"unnecessarily"},
{"hard":"supper","easy":"dinner"},
{"hard":"supplementary","easy":"extra"},
{"hard":"supplied","easy":"brought"},
{"hard":"supplying","easy":"bringing"},
{"hard":"suppose","easy":"guess"},
{"hard":"suppose","easy":"guess"},
{"hard":"supposing","easy":"assuming"},
{"hard":"supposing","easy":"if"},
{"hard":"supreme","easy":"best"},
{"hard":"surname","easy":"family name"},
{"hard":"swap","easy":"trade"},
{"hard":"swapped","easy":"traded"},
{"hard":"swapping","easy":"trading"},
{"hard":"switching","easy":"changing"},
{"hard":"synergize","easy":"combine"},
{"hard":"synopsis","easy":"summary"},
{"hard":"tactful","easy":"respectful"},
{"hard":"tactic","easy":"idea"},
{"hard":"tale","easy":"story"},
{"hard":"tame","easy":"kind"},
{"hard":"tantalize","easy":"excite"},
{"hard":"tantalized","easy":"excited"},
{"hard":"tantalizing","easy":"exciting"},
{"hard":"tardy","easy":"late"},
{"hard":"task","easy":"job"},
{"hard":"task","easy":"job"},
{"hard":"tavern","easy":"bar"},
{"hard":"tempo","easy":"speed"},
{"hard":"tenderize","easy":"soften"},
{"hard":"tenderized","easy":"softened"},
{"hard":"tenderizing","easy":"softening"},
{"hard":"tenet","easy":"belief"},
{"hard":"tenuous","easy":"unsure"},
{"hard":"terminate","easy":"end"},
{"hard":"terminated","easy":"ended"},
{"hard":"terminating","easy":"ending"},
{"hard":"terrific","easy":"great"},
{"hard":"terrified","easy":"scared"},
{"hard":"terrify","easy":"scare"},
{"hard":"terrifying","easy":"scaring"},
{"hard":"terse","easy":"short"},
{"hard":"tertiary","easy":"third"},
{"hard":"testimony","easy":"statement"},
{"hard":"texture","easy":"feeling "},
{"hard":"theories","easy":"ideas"},
{"hard":"theory","easy":"idea"},
{"hard":"thereafter","easy":"from that time on"},
{"hard":"therefore","easy":"so"},
{"hard":"thief","easy":"robber"},
{"hard":"thievery","easy":"robbery"},
{"hard":"thieves","easy":"robbers"},
{"hard":"thirtieth","easy":"30th"},
{"hard":"tho","easy":"though"},
{"hard":"thorough","easy":"complete"},
{"hard":"thoroughly","easy":"completely"},
{"hard":"thoughtful","easy":"respectful"},
{"hard":"thrive","easy":"live well"},
{"hard":"thrived","easy":"lived well"},
{"hard":"thriving","easy":"living well"},
{"hard":"throughout","easy":"during"},
{"hard":"thus","easy":"so"},
{"hard":"thwack","easy":"hit"},
{"hard":"tidied","easy":"cleaned"},
{"hard":"tidier","easy":"cleaner"},
{"hard":"tidy","easy":"clean"},
{"hard":"tidying","easy":"cleaning"},
{"hard":"timid","easy":"shy"},
{"hard":"timid","easy":"shy"},
{"hard":"tiniest","easy":"littlest"},
{"hard":"tinker","easy":"play"},
{"hard":"tinker","easy":"play"},
{"hard":"tinkered","easy":"played"},
{"hard":"tinkered","easy":"played"},
{"hard":"tinkering","easy":"playing"},
{"hard":"tiny","easy":"little"},
{"hard":"tires","easy":"wheels"},
{"hard":"title","easy":"name"},
{"hard":"titled","easy":"named"},
{"hard":"toss","easy":"throw"},
{"hard":"tossed","easy":"threw"},
{"hard":"town","easy":"city"},
{"hard":"tracked","easy":"followed"},
{"hard":"tracking","easy":"following"},
{"hard":"trail","easy":"path"},
{"hard":"trailing","easy":"following"},
{"hard":"tranquil","easy":"quiet"},
{"hard":"transferred","easy":"moved"},
{"hard":"transferring","easy":"moving"},
{"hard":"transform","easy":"change"},
{"hard":"transformed","easy":"changed"},
{"hard":"transforming","easy":"changing"},
{"hard":"transition","easy":"change"},
{"hard":"transmission","easy":"message"},
{"hard":"transmit","easy":"send"},
{"hard":"transmitted","easy":"sent"},
{"hard":"transmitting","easy":"sending"},
{"hard":"transparent","easy":"clear"},
{"hard":"trash","easy":"garbage"},
{"hard":"trashed","easy":"destroyed"},
{"hard":"treacherous","easy":"difficult"},
{"hard":"treacherous","easy":"dangerous"},
{"hard":"treatise","easy":"book"},
{"hard":"treaty","easy":"agreement"},
{"hard":"trekking","easy":"travelling"},
{"hard":"tremendous","easy":"great"},
{"hard":"tremendously","easy":"greatly"},
{"hard":"tremor","easy":"shaking"},
{"hard":"tremors","easy":"shaking"},
{"hard":"trendy","easy":"popular"},
{"hard":"triggered","easy":"started"},
{"hard":"triggering","easy":"starting"},
{"hard":"triggers","easy":"starts"},
{"hard":"triumph","easy":"success"},
{"hard":"triumphant","easy":"successful"},
{"hard":"triumphantly","easy":"successfully"},
{"hard":"trivial","easy":"unimportant"},
{"hard":"tugged","easy":"pulled"},
{"hard":"tugging","easy":"pulling"},
{"hard":"turbulent","easy":"shaky"},
{"hard":"turmoil","easy":"trouble"},
{"hard":"turmoil","easy":"trouble"},
{"hard":"turnout","easy":"crowd"},
{"hard":"tussle","easy":"fight"},
{"hard":"tussled","easy":"fought"},
{"hard":"tussling","easy":"fighting"},
{"hard":"ultimate","easy":"best"},
{"hard":"unambiguous","easy":"clear"},
{"hard":"unambiguous","easy":"clear"},
{"hard":"unambiguously","easy":"clearly"},
{"hard":"unbearable","easy":"not ok"},
{"hard":"uncanny","easy":"weird"},
{"hard":"undeniable","easy":"sure"},
{"hard":"undeniably","easy":"surely"},
{"hard":"undergarment","easy":"underwear"},
{"hard":"undergo","easy":"do"},
{"hard":"undergoing","easy":"doing"},
{"hard":"underlies","easy":"is under"},
{"hard":"underwent","easy":"did"},
{"hard":"undesirable","easy":"unwanted"},
{"hard":"unemployed","easy":"jobless"},
{"hard":"unemployment","easy":"joblessness"},
{"hard":"unethical","easy":"bad"},
{"hard":"unexpressible","easy":"unsayable"},
{"hard":"unfathomable","easy":"amazing"},
{"hard":"unfavourable","easy":"bad"},
{"hard":"unfortunately","easy":"unluckily"},
{"hard":"unilateral","easy":"one-sided"},
{"hard":"unjust","easy":"wrong"},
{"hard":"unprepared","easy":"not ready"},
{"hard":"unrecognized","easy":"unknown"},
{"hard":"unrelenting","easy":"unending"},
{"hard":"unsuitable","easy":"wrong"},
{"hard":"untrue","easy":"wrong"},
{"hard":"updating","easy":"choosing"},
{"hard":"upgrading","easy":"improving"},
{"hard":"upscale","easy":"nice"},
{"hard":"urban","easy":"city"},
{"hard":"usage","easy":"use"},
{"hard":"useful","easy":"helpful"},
{"hard":"usurp","easy":"take"},
{"hard":"usurped","easy":"took"},
{"hard":"usurper","easy":"taker"},
{"hard":"usurping","easy":"taking"},
{"hard":"utilization","easy":"use"},
{"hard":"utilized","easy":"used"},
{"hard":"utilizes","easy":"uses"},
{"hard":"utilizing","easy":"using"},
{"hard":"utopian","easy":"hopefull"},
{"hard":"vacate","easy":"leave"},
{"hard":"vacuous","easy":"empty"},
{"hard":"vague","easy":"unclear"},
{"hard":"variation","easy":"change"},
{"hard":"varies","easy":"changes"},
{"hard":"varies","easy":"changes"},
{"hard":"varieties","easy":"kinds"},
{"hard":"varieties","easy":"types"},
{"hard":"vary","easy":"change"},
{"hard":"vary","easy":"change"},
{"hard":"varying","easy":"changing"},
{"hard":"varying","easy":"changing"},
{"hard":"vast","easy":"big"},
{"hard":"vastly","easy":"greatly"},
{"hard":"veer","easy":"turn"},
{"hard":"veered","easy":"turned"},
{"hard":"veering","easy":"turning"},
{"hard":"vehement","easy":"violent"},
{"hard":"vehemently","easy":"violently"},
{"hard":"vehicle","easy":"car"},
{"hard":"veneration","easy":"respect"},
{"hard":"ventilated","easy":"aired"},
{"hard":"vexed","easy":"confused"},
{"hard":"vexing","easy":"confusing"},
{"hard":"viable","easy":"possible"},
{"hard":"vice versa","easy":"the other way round"},
{"hard":"viewed","easy":"watched"},
{"hard":"viewer","easy":"watcher"},
{"hard":"viewing","easy":"watching"},
{"hard":"violation","easy":"crime"},
{"hard":"visage","easy":"face"},
{"hard":"visualize","easy":"see"},
{"hard":"visualize","easy":"see"},
{"hard":"visualized","easy":"saw"},
{"hard":"visualized","easy":"saw"},
{"hard":"visualizing","easy":"seeing"},
{"hard":"visualizing","easy":"seeing"},
{"hard":"vitality","easy":"liveliness"},
{"hard":"voiced","easy":"said"},
{"hard":"vowed","easy":"promised"},
{"hard":"vowing","easy":"promising"},
{"hard":"voyage","easy":"trip"},
{"hard":"voyager","easy":"traveler "},
{"hard":"voyaging","easy":"traveling"},
{"hard":"vulgar","easy":"gross"},
{"hard":"wail","easy":"cry"},
{"hard":"wailed","easy":"cry"},
{"hard":"wailing","easy":"crying"},
{"hard":"waist","easy":"middle"},
{"hard":"wallop","easy":"hit"},
{"hard":"walloped","easy":"hit"},
{"hard":"warden","easy":"guard"},
{"hard":"wardrobe","easy":"clothes"},
{"hard":"warfare","easy":"war"},
{"hard":"warped","easy":"bent"},
{"hard":"warping","easy":"bending"},
{"hard":"wash","easy":"clean"},
{"hard":"washer","easy":"cleaner"},
{"hard":"washing","easy":"cleaning"},
{"hard":"we'd","easy":"we had"},
{"hard":"we'll","easy":"we will"},
{"hard":"we've","easy":"we have"},
{"hard":"wealthy","easy":"rich"},
{"hard":"weariness","easy":"tiredness"},
{"hard":"weary","easy":"tired"},
{"hard":"wedded","easy":"married"},
{"hard":"weds","easy":"marries"},
{"hard":"wee","easy":"small"},
{"hard":"weeps","easy":"cries"},
{"hard":"weepy","easy":"not strong"},
{"hard":"wham","easy":"hit"},
{"hard":"whatâd","easy":"what did"},
{"hard":"whatâve","easy":"what have"},
{"hard":"wheeze","easy":"breathe hard"},
{"hard":"where'd","easy":"where did "},
{"hard":"whereas","easy":"but"},
{"hard":"whereby","easy":"by which"},
{"hard":"wherewithal","easy":"smarts"},
{"hard":"whether","easy":"if"},
{"hard":"whether","easy":"if"},
{"hard":"whiff","easy":"smell"},
{"hard":"whilst","easy":"while"},
{"hard":"whim","easy":"sudden desire"},
{"hard":"whimper","easy":"cry"},
{"hard":"whimsical","easy":"not strong"},
{"hard":"whimsy","easy":"light"},
{"hard":"wholly","easy":"all"},
{"hard":"whom","easy":"who"},
{"hard":"whosoever","easy":"whoever"},
{"hard":"wildly","easy":"crazily"},
{"hard":"willing","easy":"ready"},
{"hard":"wimp","easy":"weak person"},
{"hard":"wise","easy":"smart"},
{"hard":"wished","easy":"wanted"},
{"hard":"wishes","easy":"wants"},
{"hard":"wishing","easy":"wanting"},
{"hard":"withdraw","easy":"remove"},
{"hard":"withdrawing","easy":"removing"},
{"hard":"withdrew","easy":"removed"},
{"hard":"witty","easy":"smart"},
{"hard":"womankind","easy":"all women"},
{"hard":"wonderful","easy":"great"},
{"hard":"wonderment","easy":"surprise"},
{"hard":"wondrous","easy":"good"},
{"hard":"worried","easy":"scared"},
{"hard":"worries","easy":"scared"},
{"hard":"worry","easy":"fear"},
{"hard":"worrying","easy":"fearing"},
{"hard":"worthwhile","easy":"important"},
{"hard":"wouldâve","easy":"would have "},
{"hard":"wouldn't","easy":"would not"},
{"hard":"yearn","easy":"desire"},
{"hard":"yearned","easy":"desired"},
{"hard":"yearning","easy":"desire"},
{"hard":"yearnings","easy":"desires"},
{"hard":"yield","easy":"give"},
{"hard":"yielded","easy":"gave"},
{"hard":"yielding","easy":"giving"},
{"hard":"yonder","easy":"there"},
{"hard":"you'll","easy":"you will"},
{"hard":"you'll","easy":"you will"},
{"hard":"you've","easy":"you have"},
{"hard":"youthful","easy":"young"},
{"hard":"youthfully","easy":"young"},
{"hard":"yup","easy":"yes"},
{"hard":"zany","easy":"crazy"},
{"hard":"zenith","easy":"top"},
{"hard":"zipping","easy":"going quickly"},
{"hard":"zips","easy":"goes quickly"},
{"hard":"all ears","easy":"listening carefully"},
{"hard":"as a last resort","easy":"if everything else fails"},
{"hard":"as to","easy":"for"},
{"hard":"at any rate","easy":"anyway"},
{"hard":"at odds","easy":"in disagreement"},
{"hard":"at once","easy":"immediately"},
{"hard":"at the drop of a hat","easy":"immediately"},
{"hard":"at the top of one's lungs","easy":"with a very loud voice"},
{"hard":"at times","easy":"sometimes"},
{"hard":"back and forth","easy":"backwards and forwards"},
{"hard":"cash cow","easy":"easy way to make money"},
{"hard":"bargain for","easy":"anticipate"},
{"hard":"bargained for","easy":"anticipated"},
{"hard":"barge in on","easy":"to interrupt"},
{"hard":"bear in mind","easy":"to consider"},
{"hard":"bear with","easy":"to be patient with"},
{"hard":"beat around the bush","easy":"to speak indirectly"},
{"hard":"birthday suit","easy":"completely naked body"},
{"hard":"black out","easy":"faint"},
{"hard":"brand-new","easy":"very new"},
{"hard":"account for","easy":"explain"},
{"hard":"all of a sudden","easy":"suddenly"},
{"hard":"as a matter of fact","easy":"actually"},
{"hard":"as soon as","easy":"when"},
{"hard":"hold on","easy":"wait"},
{"hard":"in case","easy":"if"},
{"hard":"of course","easy":"certainly"},
{"hard":"right away","easy":"immediately"},
{"hard":"show up","easy":"appear"},
{"hard":"so far","easy":"until now"},
{"hard":"stick with","easy":"continue"},
{"hard":"take over","easy":"take control"},
{"hard":"took over","easy":"took control"},
{"hard":"take place","easy":"happen"},
{"hard":"took place","easy":"happened"},
{"hard":"to the teeth","easy":"heavily"},
{"hard":"was hard up for cash","easy":"had no money"},
{"hard":"from scratch","easy":"from the beginning"},
{"hard":"don't have a cow","easy":"don't get upset"},
{"hard":"blow up","easy":"explode"},
{"hard":"blew up","easy":"exploded"},
{"hard":"bone up on","easy":"study"},
{"hard":"brush up on","easy":"improve"},
{"hard":"called off","easy":"cancelled"},
{"hard":"cheer up","easy":"become happier"},
{"hard":"chicken out","easy":"loose the courage"},
{"hard":"count on","easy":"trust"},
{"hard":"drag on","easy":"last too long"},
{"hard":"drop in","easy":"visit"},
{"hard":"drop by","easy":"visit"},
{"hard":"feel up to","easy":"feel strong enough for"},
{"hard":"find out","easy":"learn"},
{"hard":"get along","easy":"be friends"},
{"hard":"get down to","easy":"now do"},
{"hard":"get over with","easy":"end"},
{"hard":"hand in","easy":"give in"},
{"hard":"keep on","easy":"continue"},
{"hard":"laid off","easy":"fired"},
{"hard":"look after","easy":"take care of"},
{"hard":"nod off","easy":"fall asleep"},
{"hard":"pass away","easy":"die"},
{"hard":"weaselled out","easy":"got out"},
{"hard":"by the wayside","easy":"away"},
{"hard":"all of a sudden","easy":"immediately"},
{"hard":"embarked on","easy":"began"},
{"hard":"refrained from","easy":"avoided"},
{"hard":"taken for granted","easy":"not appreciated"},
{"hard":"out of the loop","easy":"not connected"},
{"hard":"accounted for","easy":"included"},
{"hard":"passed away","easy":"died"},
{"hard":"a couple of","easy":"some"},
{"hard":"spare some","easy":"give some"},
{"hard":"in opposition to","easy":"against"},
{"hard":"identical to","easy":"the same as"},
{"hard":"to and fro","easy":"around"},
{"hard":"due to","easy":"because of"},
{"hard":"in order to","easy":"to"},
{"hard":"in light of","easy":"with"},
{"hard":"chew out","easy":"tell off"},
{"hard":"with regard to","easy":"about"},
{"hard":"by means of","easy":"by"},
{"hard":"in the event that","easy":"if"},
{"hard":"until such time","easy":"until"},
{"hard":"during such time","easy":"while"},
{"hard":"in respect of","easy":"for"},
{"hard":"in view of the fact","easy":"because"},
{"hard":"on the part of","easy":"by"},
{"hard":"subsequent to","easy":"after"},
{"hard":"under the provisions of","easy":"under"},
{"hard":"in lieu","easy":"instead"},
{"hard":"adjacent to","easy":"beside"},
{"hard":"by means of","easy":"by"},
{"hard":"in the near future","easy":"soon"},
{"hard":"a few","easy":"some"},
{"hard":"pretty much","easy":"almost"},
{"hard":"what matters","easy":"what's important"},
{"hard":"on duty","easy":"working"},
{"hard":"for instance","easy":"for example"},
{"hard":"attached to","easy":"put the"},
{"hard":"as to","easy":"about"},
{"hard":"get go","easy":" beginning"},
{"hard":"don't mention it","easy":"it's ok"},
{"hard":"go bad","easy":"become bad"},
{"hard":"goes bad","easy":"becomes bad"},
{"hard":"make amends","easy":"become friends"},
{"hard":"prior to","easy":"before"},
{"hard":"enrolled in","easy":"entered"},
{"hard":"enrol in","easy":"enter"},
{"hard":"pet peeve","easy":"most unknowing thing"},
{"hard":"as a precaution","easy":"for safety"},
{"hard":"prey on","easy":"eat"},
{"hard":"preyed on","easy":"ate"},
{"hard":"praise on","easy":"eats"},
{"hard":"preying on","easy":"eating"},
{"hard":"one another","easy":"each other"},
{"hard":"in retrospect","easy":"looking back"},
{"hard":"just slightly","easy":"just a little"},
{"hard":"come about","easy":"happen"},
{"hard":"come to a stop","easy":"stop"},
{"hard":"come to a stop","easy":"stop"},
{"hard":"came to a stop","easy":"stopped"},
{"hard":"coming to a stop","easy":"stopping"},
{"hard":"come to an agreement","easy":"agree"},
{"hard":"came to an agreement","easy":"agreed"},
{"hard":"gave her word","easy":"promised"},
{"hard":"gave his word","easy":"promised"},
{"hard":"gave your word","easy":"promised"},
{"hard":"had a talk","easy":"talked"},
{"hard":"have a talk","easy":"talk"},
{"hard":"let down","easy":"disappoint"},
{"hard":"take into account","easy":"include"},
{"hard":"taken into account","easy":"included"},
{"hard":"in the right","easy":"right"},
{"hard":"in the wrong","easy":"wrong "},
{"hard":"in the name of","easy":"for"},
{"hard":"in motion","easy":"moving"},
{"hard":"of use","easy":"helpful"},
{"hard":"of no use","easy":"not helpful"},
{"hard":"blew up","easy":"exploded"},
{"hard":"non compliant","easy":"disagreeable"},
{"hard":"a great deal more","easy":"a lot more"},
{"hard":"a great deal less","easy":"a lot less"},
{"hard":"figure out","easy":"learn"},
{"hard":"figured out","easy":"learned"},
{"hard":"out of date","easy":"old"},
{"hard":"deal with","easy":"handle"},
{"hard":"a few","easy":"some"},
{"hard":"pretty much","easy":"almost"},
{"hard":"what matters","easy":"what's important"},
{"hard":"on duty","easy":"working"},
{"hard":"for instance","easy":"for example"},
{"hard":"attached to","easy":"put the"},
{"hard":"as to","easy":"about"},
{"hard":"hands down","easy":"definitely"},
{"hard":"taken aback","easy":"surprised"},
{"hard":"on awful lot","easy":"a lot"},
{"hard":"such time","easy":"the time"},
{"hard":"such a time","easy":"the time"},
{"hard":"due time","easy":"some time "},
{"hard":"responding to","easy":"answering"},
{"hard":"responded to","easy":"answered"},
{"hard":"child's play","easy":"easy"},
{"hard":"childs play","easy":"easy"},
{"hard":"rather than","easy":"instead of"},
{"hard":"partake in","easy":"do"},
{"hard":"pull through","easy":"survive"},
{"hard":"track down","easy":"find"},
{"hard":"full blastâtop speed"},
{"hard":"pipe down","easy":"quiet"},
{"hard":"pined for","easy":"missed"},
{"hard":"pining for","easy":"missing"},
{"hard":"pine for","easy":"miss"},
{"hard":"in a pinch","easy":"in an emergency"},
{"hard":"aversion to","easy":"dislike of"},
{"hard":"pertained to","easy":"involved"},
{"hard":"pertaining to","easy":"involving"},
{"hard":"pertain to","easy":"involve"},
{"hard":"a nuisance","easy":"annoying"},
{"hard":"preferred to","easy":"liked to"},
{"hard":"preferring to","easy":"liking to"},
{"hard":"prefer to","easy":"like to"},
{"hard":"sexual intercourse","easy":"sex"},
{"hard":"dawn on","easy":"come to"},
{"hard":"down in the dumps","easy":"sad"},
{"hard":"be obliged to","easy":"be happy to"},
{"hard":"doze off","easy":"fall asleep"},
{"hard":"nooks and crannies","easy":"small parts"},
{"hard":"adjacent to","easy":"aside"},
{"hard":"adverse to","easy":"against"},
{"hard":"opposed to","easy":"against"},
{"hard":"sought after","easy":"look for"},
{"hard":"prey on","easy":"eat"},
{"hard":"preyed on","easy":"ate"},
{"hard":"preys on","easy":"eats"},
{"hard":"preying on","easy":"eating"},
{"hard":"bona fide","easy":"real"},
{"hard":"bear the burden","easy":"have the trouble"},
{"hard":"the gross majority","easy":"most"},
{"hard":"the majority of","easy":"most of"},
{"hard":"scene of the crime","easy":"place of the crime"},
{"hard":"abide by","easy":"follow"},
{"hard":"over and over","easy":"many times"},
{"hard":"abiding by","easy":"following"},
{"hard":"abided by its","easy":"followed"},
{"hard":"abides by","easy":"follows"},
{"hard":"response to","easy":"answer"},
{"hard":"being facetious","easy":"joking"}
]
